### ISSUE TITLE
Incorrect info in Zictionary about finesse (or wrong Techmino finesse behavior)

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1004]
Zictionary (or TetroDictionary) states that in this game:
- holding the same piece as the one currently controlled, or
- moving a piece, then holding

are considered finesse faults.
![IMG_20231006_182620](https://github.com/26F-Studio/Techmino/assets/125081901/31e51e25-43f3-48bf-860d-3128ea3eb1dd)

However, that's not the case.

https://github.com/26F-Studio/Techmino/assets/125081901/1036236e-651c-4150-bd23-b0aca665a1ef

(notice that despite both moving a piece before holding and after swapping for the same piece, the game doesn't count that as finesse fault - finesse combo is still yellow)

**Comment by SweetSea-ButImNotSweet** [comment]
Can someone assign @C29H25N3O5 into this issue?

**Comment by MrZ626** [comment]
oh, this is an old feature, it was deleted some time ago
