### ISSUE TITLE
Cold Clear Replay Error

### ISSUE THREAD

**Issue by sailyncaenfer** [26F-Studio/Techmino#1014]
In custom game, Cold Clear's replays do not follow its movements from the original plays.

https://media.discordapp.net/attachments/704004757047738448/1164026414278910002/Screen_Recording_20231018_102242.mp4?ex=6541b713&is=652f4213&hm=04b8f55280097fd551a187489869ada279cf0d75c5e704ed848a9b7d579feae7&

Steps on how to reproduce the bug:
- Start screen recording (Optional)
- Open Techmino and start a CC battle
- End the game, making sure to give the bot some time to do something, then stop screen recording
- Compare the replay to your recorded video or original play

**Comment by sailyncaenfer** [comment]
> uhhh wtf how did you get the replay button to appear? that's not supposed to happen, like, at all

oh what
idk, it just happened to be there. i dont remember doing anything that could cause the replay button to appear.

**Comment by MrZ626** [comment]
yeah, the replay button shouldn't appear in vs modes

**Comment by MrZ626** [comment]
oh I know, because I fixed a bug some weeks ago, lost players will really disappear, so the replay button thinks current mode is a singleplayer mode then appears
LMAO

**Comment by MrZ626** [comment]
fixed

**Comment by MrZ626** [comment]
waiting for his better fixing, which will not conflict with a PR
