### ISSUE TITLE
Incorrect grading in Secret Grade

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1021]
Secret Grades are 1 grade lower than the correct grade (like you would except in TGM).

For example: This is supposed to be GM (19 lines), 18 are being detected.
![Screenshot_2023-10-22-14-50-00-976_org f26_studio Techmino](https://github.com/26F-Studio/Techmino/assets/125081901/a16363ac-3758-4d46-910e-7e6274618aa3)
This also can cause the player to get Grade 11 with -1 lines.
![Screenshot_2023-10-22-14-50-27-950_org f26_studio Techmino](https://github.com/26F-Studio/Techmino/assets/125081901/0f210933-69fa-4f5d-bf68-0eb45729ea0a)

**Comment by SweetSea-ButImNotSweet** [comment]
@Not-A-Normal-Robot is this bug solved?

**Comment by KonSola5** [comment]
A question: How to download the latest **snapshot**?

**Comment by KonSola5** [comment]
Yes, it does.
![GM](https://github.com/26F-Studio/Techmino/assets/125081901/83554f7e-3de2-4804-aaab-eb7c76f390a9)
