### ISSUE TITLE
180 rotation in BiRS is not symmetric

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#1022]
- The `1<->3` 180 rotations of `SZ`, `PQ`, `FE`, `L5J5`, `YR`, `HN` should be symmetric between each pair, but they are not. `JL` and `S5Z5` were repaired long ago in decbde8 and 850a31d, respectively.
- The `0` state and `3` state of `W` are symmetric to each other, and so do the `1` and `2` states. So `0->2` of `W` should be symmetric to `3->1`, but they are both `R`. Similarly, `2->0` and `1->3` should be symmetric, but they are both `L`.

**Comment by MrZ626** [comment]
adf225e
