### ISSUE TITLE
Import/Export the custom game data

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#1031]
### What feature do you want to suggest to the game?
Right now we can only import and export mission, field and sequence
How about we can include more data? About mods, bot and other arguments?

P/s: we should add an button to allow us to export the data to legacy format (and import too) (only mission, field and sequence like the game at the moment)
![image](https://github.com/26F-Studio/Techmino/assets/106439598/86b655b8-a26f-4d88-a924-e2bcdc68f3b1)

**Comment by SweetSea-ButImNotSweet** [comment]
@ImpleLee Ping

**Comment by ImpleLee** [comment]
Currently I am kind of busy on some other matters. Maybe you can first try it out by yourself? Or you can maybe wait MrZ to solve this, since I think he will also agree to solve when he has time...

**Comment by KonSola5** [comment]
This was also mentioned by me in #1003.

**Comment by SweetSea-ButImNotSweet** [comment]
Seems duplicated :(
