### ISSUE TITLE
Inconsistency regarding the HPC term

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1034]
## Action text:
Hemi-Perfect Clear
## Voice packs:
- Miya - Half Clear
- Mono - Half Perfect Clear
- Xiaoya - Half Clear
- Flore - Half Clear
- Miku - Clear
- Zundamon - Half Clear / Clear

https://github.com/26F-Studio/Techmino/assets/125081901/ebde6266-2f76-480c-9de1-57ad4ef0ed95

## The (?) section:
Half Perfect Clear
![hpc_info](https://github.com/26F-Studio/Techmino/assets/125081901/377a256e-59d7-4ab7-acc9-9d47f00748a1)

## Zictionary (or TetroDictionary):
Half Perfect Clear
![hpc_zictionary](https://github.com/26F-Studio/Techmino/assets/125081901/da805f98-9a73-492a-86b5-22782b4e033e)

I think the action text should be renamed to "Half Perfect Clear" or "Half Clear".

**Comment by ImpleLee** [comment]
There were some fights around this term in dev group, and the options are the following:
- `half clear`,
- `half perfect clear`,
- `hemi-perfect clear` (credit to @Neubulae),
- `clear`,

sorted from my favorite term (`half clear`) to my least favorite term (`clear`).

Their abbreviation was always `HPC`.

**Comment by MrZ626** [comment]
Texts have been editted now
but audios are hard to change

**Comment by ImpleLee** [comment]
You can call the inconsistency between the text and the audio a feature, since audio needs to be shorter naturally.

**Comment by KonSola5** [comment]
*slight off-topic*
Especially since there are voicepacks which don't necessarily only say "Perfect Clear" on PC:
Mono can alternatively say "All Clear", and Zundamon exclusively says "All Clear".
