### ISSUE TITLE
Wrong Z orientation / turn 

### ISSUE THREAD

**Issue by MagicUserLast** [26F-Studio/Techmino#1035]
Images: 

![Untitled](https://github.com/26F-Studio/Techmino/assets/33360427/252fad14-05b5-4bbb-88c0-7a58061a7ccf)
![4](https://github.com/26F-Studio/Techmino/assets/33360427/abee2ff5-d151-448d-8aa2-ea9004a38d7c)
![sisrotation](https://github.com/26F-Studio/Techmino/assets/33360427/6806e054-019e-485f-9050-679ddfe40f3e)
![exampleSpiece](https://github.com/26F-Studio/Techmino/assets/33360427/fec442e7-090e-4109-a458-3f34630f9ef7)

I have tested only in the three sprints modes 10l,20l and 40l mobile(ANDROID Version ) . 
When i try to rotate Z piece it is in the wrong orientation . 
And could see the orientation of the piece it is wrong before turn . (its compare with the image of the S piece )

Example :
1- try to turn Z piece to right ,the Z piece go left 
![2](https://github.com/26F-Studio/Techmino/assets/33360427/237d9fff-c89d-4e91-9139-a43dbf24a361)

              2- try to turn Z piece to left , the Z piece go to right 
![3](https://github.com/26F-Studio/Techmino/assets/33360427/7a4076f4-243d-4f05-bb4f-3f6943075c81)

**Comment by MrZ626** [comment]
you accidentally set it yourself.
press the "style" button in the 3rd image to fix it
have you seen the white dot? it should be at lower part of the piece

**Comment by MrZ626** [comment]
oops thx
