### ISSUE TITLE
Invisible blocks on the page of custom field editing is invisible

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#1037]
Invisible blocks are invisible when editing custom field, making it hard for the user to know whether a certain block is filled with invisible block or just not filled, when user just want to use the feature of invisible block.

The recommended solution is to use a special texture, like the one used in replay of invisible modes.

(First found by @User670.)

**Comment by SweetSea-ButImNotSweet** [comment]
Could we use the same texture that used for invisible blocks when in TAS mode?

**Comment by MrZ626** [comment]
fixed
