### ISSUE TITLE
4-digit commit hashes used in version numbers does not uniquely identify a commit

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino#1040]
snapshots have version numbers that end in `@`+4 hexadecimal numbers that are meant to represent the hash of the commit. However, 4 digits of hash doesn't seem to be able to uniquely identify a commit.

![image](https://github.com/26F-Studio/Techmino/assets/22617255/20689f18-9ab7-425e-a101-eb0f86d10490)

As an example, this commit: `https://github.com/26F-Studio/Techmino/commit/55800e307ffc52640502b81bcfe52dc5fa94d632` ( https://github.com/26F-Studio/Techmino/commit/55800e307ffc52640502b81bcfe52dc5fa94d632 )

We can truncate the hash down, and GitHub is still able to uniquely identify this commit: `https://github.com/26F-Studio/Techmino/commit/55800e3` ( https://github.com/26F-Studio/Techmino/commit/55800e3 )

However, truncating it down to 4 digits makes GitHub show a 404 page: `https://github.com/26F-Studio/Techmino/commit/5580` ( https://github.com/26F-Studio/Techmino/commit/5580 )

I don't know if "being able to trace back to the commit from version number" is desired or not. If yes, then a 4-digit commit hash isn't gonna do it. Maybe use 7, like GitHub web does for the time being.

(ps. for a repo with more commits, like `musescore/MuseScore` or `ppy/osu`, 5 digit hash also gives a 404, requiring 6 digits to identify a commit, one more digit than Techmino.)

**Comment by ImpleLee** [comment]
git can figure out how many digits is needed by itself. One way to do that is the following:
```bash
git rev-parse --short=4 HEAD
```

It will output 4 digits when it is unique, but automatically use more than 4 digits if needed.

**Comment by ImpleLee** [comment]
Found the idea of 4-digit commit hash was introduced in #176 .

**Comment by ImpleLee** [comment]
Maybe we can now just use whatever git gives us, like typically a 7 or 8 digit commit hash? I personally do not think that will hurt the appearance very much... @MrZ626 .
One alternative is to use a at-least 4 digit solution, but if git gives us a 4-digit hash, that only means the 4-digit hash is unique now, but it cannot prevent any future conflicting commit hash with the same 4 digit prefix...

**Comment by shoucandanghehe** [comment]
> It will output 4 digits when it is unique, but automatically use more than 4 digits if needed.

What does github do if a subsequent commit makes this hash not unique anymore?

**Comment by ImpleLee** [comment]
> > It will output 4 digits when it is unique, but automatically use more than 4 digits if needed.
> 
> What does github do if a subsequent commit makes this hash not unique anymore?

Probably 404. Considering such cases, I do prefer whatever git gives us (typically a 7 or 8 digit hash).

**Comment by MrZ626** [comment]
4-digit is enough, it's not necessary to make it 100% unique, and even 8 digits cannot guarantee

**Comment by MrZ626** [comment]
It's for comparing different screenshots' version. If you want locate the exact commit, find it yourself
