### ISSUE TITLE
ignore this i don't know how to delete

### ISSUE THREAD

**Issue by coralphoenix76** [26F-Studio/Techmino#1042]
### What feature do you want to suggest to the game?

something ti save an ongoing game and come back later

**Comment by SweetSea-ButImNotSweet** [comment]
Duplicate of #955
@Not-A-Normal-Robot

**Comment by coralphoenix76** [comment]
> Duplicate of #955
> @Not-A-Normal-Robot

deleted (i think)

**Comment by SweetSea-ButImNotSweet** [comment]
> > Duplicate of #955
> > @Not-A-Normal-Robot
> 
> deleted (i think)

You cannot deleted this issue
Also please close it as **NOT COMPLETED**

**Comment by coralphoenix76** [comment]
> > > Duplicate of #955
> 
> > > @Not-A-Normal-Robot
> 
> > 
> 
> > deleted (i think)
> 
> 
> 
> You cannot deleted any issues
> 
> Also please close it as **NOT COMPLETED**

how do i open it again?

**Comment by SweetSea-ButImNotSweet** [comment]
> > > > Duplicate of #955
> > 
> > 
> > > > @Not-A-Normal-Robot
> > 
> > 
> > > 
> > 
> > 
> > > deleted (i think)
> > 
> > 
> > You cannot deleted any issues
> > Also please close it as **NOT COMPLETED**
> 
> how do i open it again?

There is a button named Reopen the issue at the bottom of the page
