### ISSUE TITLE
Add TV remote support

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#1058]
I'm not really kidding but uh, Techmino experience on TV right now is suck if you don't have a Bluetooth keyboard (really)
I even can't go to ``test`` scene :(
Most keys on remote didn't work

At least Techmino and CCLoader works fine

**Comment by User670** [comment]
I'm gonna do a bad thing and just close this as not planned. Sorry MrZ if you somehow intend to support Android TVs.

**Comment by SweetSea-ButImNotSweet** [comment]
@User670 please remove the "iOS" tag
I haven't seen any TV that made by Apple before...

**Comment by SweetSea-ButImNotSweet** [comment]
> I'm gonna do a bad thing and just close this as not planned. Sorry MrZ if you somehow intend to support Android TVs.

Eh what? What do you mean?
