### ISSUE TITLE
[FEATURE REQUEST] Add Custom Music function 

### ISSUE THREAD

**Issue by TasziteOst** [26F-Studio/Techmino#1068]
### What feature do you want to suggest to the game?
This function will allow people to listen to their favorite music while playing, etc., as they would not need to turn off the game's music and open a music platform such as Spotify, AppleMusic, etc. This Function could be implemented in "Custom" Mode, or in Settings > Sound, 
Since it already has customization of the Background and Tetriminos, I thought this would be a good idea. (I Think)

**Comment by shoucandanghehe** [comment]
Hi, do you mean letting the game play the player's own audio files?

Well first of all `Techmino` is a game and not a music player, as you said we just need to turn off the game music and turn on other real music players.

Use the right stuff for the right thing.

For game backgrounds and mino skins, this is something that _**can only**_ be implemented by the **_game itself_**, and is fundamentally different from what you want, I hope you understand.

**Comment by SweetSea-ButImNotSweet** [comment]
Just a reminder: this can be only a thing when the game is ported to LOVE 12 (11.4 right now, 12 is not released yet)
When? I don't know, don't ask me!
