### ISSUE TITLE
Modes don't unlock in single player mode (Android)

### ISSUE THREAD

**Issue by cddls** [26F-Studio/Techmino#1078]
Screenshot with unintended behaviors (*Image(s) Here*):
![Screenshot_20240113_215732_org f26_studio Techmino](https://github.com/26F-Studio/Techmino/assets/156546421/8e4193e5-eeff-4c29-8dce-2fe13b1a12d9)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):

When using single player mode, i'm unable to advance further than the 40L sprint. I've reached rank B and higher in the 40L, 20L, and 10L sprint, but the game does not register, that at all for the 40L sprint. Also, I've reached higher ranks in the previous modes, however it only shows that I've completed these in rank B. I've already tried re-installing the app but no changes. Would love to be able to keep advancing. Thank you :)

**Comment by cddls** [comment]
Hey, thank you. As i said, I have reached level B or higher in the 40L multiple times, it just doesn't register that and doesn't unlock further levels.

![Screenshot_20240113_224413_org f26_studio Techmino](https://github.com/26F-Studio/Techmino/assets/156546421/fdf514b2-291d-4b94-8e3b-6f43c19573ab)

**Comment by MrZ626** [comment]
that's finsse rank, not mode rank

**Comment by cddls** [comment]
oh i see, thank you! I thought they meant the same thing.
