### ISSUE TITLE
English mode name suggestions

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1088]
## What feature do you want to suggest to the game?
Changing some mode names and/or descriptions:
## Mode names
Zen 200 → Zen 200L
Tech VS 49/99 → Techmino 49/99 *(like the internal titles of those battle royale modes)*
Tech B2B → Tech
Infinite: Dig → Dig INFINITE
Inf. PC Challenge → PC Challenge INFINITE
C4W Training → Sprint 100 COMBO *(disputable?)*
Sprint EFFICIENCY -> Efficiency 40L *(this isn't a time attack, like a name would suggest)*

### Tech modes:
Try to keep the Back-to-Back chain! → Send 100 lines as fast as you can while keeping the Back-to-Back chain!
### Tech+ modes:
Spins & PCs only → Send 100 lines as fast as you can performing only spins and PCs!
### Backfire modes:
Hold back the backfiring garbage lines → Send 100 lines as fast as you can while attacking yourself!
### PC Challenge modes:
Get PCs within 100 lines! → Get as many PCs as you can within 100 lines!
### Inf. PC Challenge:
Get PCs as much as you can! → Get as many PCs in a row as you can!
### Sprint Efficiency / Efficiency 40L:
Send more attack in 40 lines! → Send as many lines as possible within 40 lines!
### Tech FINESSE:
No finesse errors! → Send 100 lines as fast as possible while keeping perfect finesse!
(*finesse modes should be 40L sprints rather than 100 attack sprints, since in 100 attack sprints you go for spins*)
### C4W Training:
Infinite combos → Perform as many combos as you can within 100 lines! *(or something else to signify that the mode ends after clearing 100 lines)*
### Drought 100L:
100L but without I blocks → 100L but without I **pieces** *(blocks generally refer to locked minoes on the board)*
### Drought+ 100L:
W. T. F. → WTF
### Classic:
A \_\_\_\_-speed recreation game from the 80s → A \_\_\_\_-speed recreation **of a** game from the 80s
### Battle EASY/NORMAL/HARD:
Defeat the AI! → Defeat the AI **as fast as you can!** *(the mode is ranked based on how fast you complete it)*

# 0.17.16 update
### Dig TECHRASH 10L:
Dig 10 garbage lines using only techrash! → Dig 10 garbage lines while only clearing Techrashes!

**Comment by KonSola5** [comment]
![techmino49](https://github.com/26F-Studio/Techmino/assets/125081901/af656d9f-2067-4be5-a75f-32a8ecef1ef9)
Fits perfectly.
Fun fact: Inf. PC Challenge is longer.

**Comment by ImpleLee** [comment]
Maybe you could just send a pull request? We can discuss finer adjustments line by line.
