### ISSUE TITLE
Incorrect SRS-X 180-degree kicks

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1090]
Some examples comparing Techmino and Cambridge (Cambridge accurately replicates SRS-X).

# 180-degree T kick:
## Cambridge:
https://github.com/26F-Studio/Techmino/assets/125081901/cd90df4e-ce65-4d62-960e-da62758b1042
## Techmino:
https://github.com/26F-Studio/Techmino/assets/125081901/318efa73-a3af-4bc6-bfbf-0c3b07bbd024

# 180-degree Z kick:
## Cambridge:
https://github.com/26F-Studio/Techmino/assets/125081901/80feb4c6-8dad-4da0-890f-265ab4889c99
## Techmino:
https://github.com/26F-Studio/Techmino/assets/125081901/0a7e74a4-f0e0-4750-a3c6-34b681488579

There are probably more.

**Comment by SweetSea-ButImNotSweet** [comment]
~~Lại là một câu chuyện thiếu kick/sai thứ tự kick lần nữa~~
Welp I will have a look at it soon

**Comment by KonSola5** [comment]
Some useful references:
## Heboris (the first game with SRS-X)
https://github.com/nightmareci/HeborisC7EX-SDL2/blob/9e1dba56baf20a940dbade99bda529fedbbf7d7f/src/script/world.c#L121-L135

**Comment by MrZ626** [comment]
oh no I missed this issue, sorry!!
it's intended to be different from other games, we really don't need to implement other SRS-X here
