### ISSUE TITLE
T piece doesn't kick upwards in ARS

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1094]
Because ARS_Z looks like it's supposed to follow TGM3 ARS, since the I piece can kick upwards, according to https://tetris.wiki/Arika_Rotation_System, the T-piece should also be able to kick upwards. However, it doesn't do that.

Observe the inputs.

https://github.com/26F-Studio/Techmino/assets/125081901/e860931d-dda5-4aca-9768-393a67ab4ecb

**Comment by KonSola5** [comment]
Similarly, the I-piece doesn't kick off the walls, only off the floor.

**Comment by MrZ626** [comment]
ARS_Z is not designed to follow original ARS, but it seems that I should make it a bit more powerful

**Comment by KonSola5** [comment]
Though here it's understanable - the rotation system is called "ARS**_Z**".
