### ISSUE TITLE
Language and (i) buttons don't work

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1098]
Clicking on the Language button:
1. Focuses the (i) button,
2. Tries to click on the (i) button, but fails,
3. Enters the (?) section.

Clicking on the (i) button:
1. Clicks on the (i) button, but fails,
2. Enters the (?) section.

Edit: On mobile, aforementioned buttons don't work at all.

https://github.com/26F-Studio/Techmino/assets/125081901/2abb5eae-4695-487a-afef-643936242aa1

**Comment by MrZ626** [comment]
fixed
