### ISSUE TITLE
ColdClear can be initialized with Skip Hold

### ISSUE THREAD

**Issue by KonSola5** [26F-Studio/Techmino#1106]
This results in this mess, as CC doesn't expect that behavior:
![Screenshot_2024-03-26-09-15-40-542_org f26_studio Techmino](https://github.com/26F-Studio/Techmino/assets/125081901/0a755d3c-c9ea-466a-8470-860dee4a9780)

To reproduce:
1. Go to Custom Game.
2. Change the Hold mode to Skip.
3. Change the opponent to CC.
4. Watch CC's board getting absolutely messy.

**Comment by ImpleLee** [comment]
fixed in #1163 .
