### ISSUE TITLE
Techrash modes have ranking issue

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#1120]
Screenshot with unintended behaviors (*Image(s) Here*):
![image](https://github.com/26F-Studio/Techmino/assets/106439598/176b2e95-bec5-439d-9eea-edebb2ea691f)
![image](https://github.com/26F-Studio/Techmino/assets/106439598/90164888-2f70-4ea0-8106-2a5de4aebe04)
The game was modified to force showing the current rank in replay

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
1. Playing Techrash Normal or Techrash Ultimate
2. Reach the A rank and notice the showing rank
    * Techrash Normal: 30 Techrashes
    * Techrash Ultimate: 8 Techrashes
3. Now clear more a Techrash and notice the showing rank again. It's... odd

**Comment by MrZ626** [comment]
fixed
