### ISSUE TITLE
(Bug) Invisible blocks are visible when watching TAS replays

### ISSUE THREAD

**Issue by wahoo-man83** [26F-Studio/Techmino#1123]
Screenshot with unintended behaviors (*Image(s) Here*):
!
![image_2024-06-17_212924713](https://github.com/26F-Studio/Techmino/assets/173120359/d274a554-b013-4a7e-9a1e-49b90346b22e)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
1. Do a TAS run an any invisible mode
2. When playing TAS mode you can see the invisible blocks as a TAS tool
3. Save as replay
4. When you watch the replay they still have the TAS tool visibility

**Comment by shoucandanghehe** [comment]
I don't understand what you mean.
But invisible blocks should be visible in replay, with or without tas

**Comment by SweetSea-ButImNotSweet** [comment]
@shoucandanghehe I think it can be closed now
Anyway, I think the issue reporter expected invisible blocks should not be shown in replay, like the default in Nullpomino (but we can trigger the show invisible blocks option, right? I believe).
