### ISSUE TITLE
C4W Practice (Normal) Prioritizes time on scoreboard

### ISSUE THREAD

**Issue by FrickTown** [26F-Studio/Techmino#1126]
Screenshot with unintended behaviors (*Image(s) Here*):
![Screenshot_20240627-111354](https://github.com/26F-Studio/Techmino/assets/173141821/e511f3eb-da46-409e-a3e4-ed36664a8ade)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):

Score 10+ combo on Normal C4W Training and lose as quickly as possible to get record.

**Comment by KonSola5** [comment]
Probably related: #1082

**Comment by MrZ626** [comment]
already fixed (0.17.17)

**Comment by ImpleLee** [comment]
So hard to say it is fixed, since ... well, we don't know why MrZ wants to make this mode feel so weird.
