### ISSUE TITLE
When I try to listen to music I get a blue screen

### ISSUE THREAD

**Issue by m4kurqneko** [26F-Studio/Techmino#1135]
![26](https://github.com/user-attachments/assets/27f65cdf-64a1-4327-b4d5-af5283f61094)
Press ♫ on the title screen to go to this screen.
Also, the background music that normally plays doesn't play.
I noticed this while I was writing this,「Last Played: C4W Training」Selecting this fixed it.
I don't know because it can't be done in custom games.
Sorry if this is a bug that has already been discovered.
(This sentence was translated by Google, so there are some inaccuracies. I usually use Japanese. If you understand Japanese but don't understand this text, we can send it to you in Japanese.)

**Comment by shoucandanghehe** [comment]
try update to latest version (0.17.21)
