### ISSUE TITLE
Latest Xcode segfaults in our CI

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#1153]
We are currently going back to XCode 15.3 in our CI, so this is just a tracking issue, and we can close it when we can comfortably use a latest version of XCode.

There is [a similar post](https://forums.developer.apple.com/forums/thread/757398) on Apple Forum.

**Comment by ImpleLee** [comment]
Upstream issue on love repo: love2d/love#2099 .

**Comment by MrZ626** [comment]
seems that we don't need to consider it anymore
