### ISSUE TITLE
replay freezes at 0f

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#1158]
## How to reproduce

1. start the techmino in current HEAD
2. play 40l until the game ends
3. hit the `replay` button

## What happened
The screen stops at this frame.
![Screenshot_20241014_160523-2](https://github.com/user-attachments/assets/f036632c-1bbf-4b4e-b790-9c1a9e97058f)

## Expected behavior
The replay can be played normally.

## Extra information
Bisecting shows the bug starts at commit b73a6533 .

**Comment by MrZ626** [comment]
(forgot to close issue)
