### ISSUE TITLE
Make marathon follow global DAS/ARR settings

### ISSUE THREAD

**Issue by washikano** [26F-Studio/Techmino#1162]
Hello ^^ currently marathon modes (endless, 200L, etc.) and zen mode have their own hard-coded DAS/ARR settings, it would be nice if they obeyed global DAS/ARR settings like Sprint modes do

EDIT: I noticed that marathon _does_ follow global DAS/ARR but up to a certain point; if  DAS/ARR is set to very low values (between 1F - 5F, needs more testing) marathon will ignore them

**Comment by shoucandanghehe** [comment]
https://github.com/26F-Studio/Techmino/blob/396293c8af1397bb8b62adaad0428a03cdd9a688/parts/modes/marathon_bfmax.lua#L4

Currently Marathon does have a minimum das/arr limit, which is part of the game design.
I think your needs can be realized through the mod system, but right now the mod system is basically unavailable and needs to be refactor

**Comment by ImpleLee** [comment]
Zen mode does obey the global das/arr settings.
Marathon modes are designed in this way.

**Comment by washikano** [comment]
What a shame. Other games like Apotris have Marathon modes that follow global DAS/ARR except for specific modes like Classic/NES mode. I don't see a reason why it should be limited but that was your decision, so I'll leave it at that.

Thank you anyway.

**Comment by MrZ626** [comment]
Sorry but this is designed as this because:
1. 0arr will make high gravity feels not exist, then marathon degrades to sprint
2. non-0arr make gameplay more interesting on visual, and provide a feel of rhythm, which I think it's good
so actually marathon mode are intended to be in 20G-series, then high DAS/ARR is resonable
