### ISSUE TITLE
my block goes transparent

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#1167]
After #1164 , I can no longer see my blocks.
This was privately reported to MrZ, so this is just a reminder.

https://github.com/user-attachments/assets/cbb5e2f2-02b5-41b4-8cb0-cda1317159cb

**Comment by SweetSea-ButImNotSweet** [comment]
Fixed

**Comment by ImpleLee** [comment]
Now my previously block skin goes away and becomes 'Crystal (Scf)'. Does the naming change **have to** bother the user's own settings?

**Comment by MrZ626** [comment]
Just fallback to the default skin when current one not found
Yes, all skins' name changed to a more readable one, so old settings become invalid
oh I forget to close this issue

**Comment by ImpleLee** [comment]
Does not sound like what is usually done in the `main.lua`.
