### ISSUE TITLE
show commit hash in version code in nightly version

### ISSUE THREAD

**Issue by flaribbit** [26F-Studio/Techmino#176]
e.g. `Nightly V0.16.0 5b4fd89`

**Comment by MrZ626** [comment]
![image](https://user-images.githubusercontent.com/54570947/128641656-c474c0f7-dcd0-4b52-9864-88a86c56dd48.png)
自动打包的时候把string="xxx" 改成 string="V${三段版本号}#${提交hash}"
例如: string="V0.16.0#abcdef"
