### ISSUE TITLE
Show the height of stacking on stacking mode

### ISSUE THREAD

**Issue by Allustrate** [26F-Studio/Techmino#196]
In the stacking mode, some players may forgot how high they have stacked. Thus this feature may help players in these situations.

The hight can be displayed on the upper-right of the stacks, just like the incoming attack; or shown at the left of the screen, near the "blocks" statistics.

**Comment by shoucandanghehe** [comment]
I like this
![image](https://user-images.githubusercontent.com/51957264/129318986-a47a464b-ffe9-4b21-97cc-a2a33e982392.png)
