### ISSUE TITLE
Swipe to switch between view radar chart and stats on endgame page

### ISSUE THREAD

**Issue by Allustrate** [26F-Studio/Techmino#197]
Currently (V0.16.0), radar chart and stats are shown in two different pages, and player may click/tap the "<" or ">" button to switch. 

But for mobile phone players, they may be confused if they can not swipe to switch between the two pages.

**Comment by Trebor-Huang** [comment]
Maybe add an event listener in Zframework?

When there is a relatively quick movement starting on a widget, it should be detected as a swipe (or, a flick in rhythm game terminology).
Swipe-scrolling seems next to impossible to implement for now.

**Comment by MrZ626** [comment]
The problem is, that's not a widget
Oh, so I can add a transparent button on it

**Comment by Trebor-Huang** [comment]
Well that's so... Z-ish

**Comment by Trebor-Huang** [comment]
Also, you can implement a container component, that just contains some widgets and stuff, so that scrolling is easier to make.

**Comment by SweetSea-ButImNotSweet** [comment]
Finally, the owner of this FR can feel comfortable now?

**Comment by Allustrate** [comment]
Glad that this feature has been finally added to the game. Unfortunately, as I am currently in hospital and was not accessible to my laptop, where I usually play Techmino, I am temporarily not able to experience this new amazing feature. However, I would express my gratitude to the guy who made this feature possible.



---Original---
From: "C6H12O6 + NaCl + ***@***.***&gt;
Date: Sun, Oct 29, 2023 16:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [26F-Studio/Techmino] Swipe to switch between view radar chartand stats on endgame page (#197)




 
Finally, the owner of this FR can feel comfortable now?

**Comment by SweetSea-ButImNotSweet** [comment]
I'm so sorry to hear about this, wish you could get better soon
