### ISSUE TITLE
Target line doesn't have smooth falling animation

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#208]
In a mode where line delay is not 0, if there is a target line, when a line is cleared, the target line moves downwards very fast without animation that is consistent with other things like the field or the blocks.

Sorry, no screenshot is currently available for me.  But since this issue is mentioned in the dev group, Most devs should know what is described here.

This issue is discovered by @user670 .

**Comment by user670** [comment]
I guess I should clarify what I was complaining about

When there is a lock delay, the target line moves down at the beginning of the delay but the blocks move down at the end of the delay. I'm complaining about the difference in timing here. (There is no smooth falling to be expected.)

**Comment by MrZ626** [comment]
You are right, it's really simple to fix
