### ISSUE TITLE
重构 Android CI

### ISSUE THREAD

**Issue by shoucandanghehe** [26F-Studio/Techmino#215]
- [x] 使用源码编译出包
- [x] 快照版本更改包名
- [x] 快照版本替换icon
- [x] 打包CC
- [x] 签名

**Comment by shoucandanghehe** [comment]
点错了（

**Comment by Trebor-Huang** [comment]
I'm almost done. Just need to tweak a few places. But after I submit my code, you still need to integrate it with the automatically-choose-release-or-snapshot-ci thing. I'll do what I can to ease the process.

**Comment by Trebor-Huang** [comment]
#218
