### ISSUE TITLE
CC出现垃圾行即自杀

### ISSUE THREAD

**Issue by shoucandanghehe** [26F-Studio/Techmino#224]
https://user-images.githubusercontent.com/51957264/130383472-d85ee0d0-4e1a-48f2-a3e0-7dab114c4ca3.mp4

*本测试使用PR代码以及配套CC
~~因为旧的会直接闪退，且似乎自杀情况也存在~~

**Comment by Trebor-Huang** [comment]
修复： Trebor-Huang/cold_clear_ai_love2d_wrapper@4cbec79

**Comment by MrZ626** [comment]
CC is being refactored and this is not a bug in stable version, so this issue is not necessary

**Comment by Trebor-Huang** [comment]
It's actually an absent-minded mistake in the wrapper.
