### ISSUE TITLE
Master - Phantasm doesn't keep its color from the final phase into replays

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#226]
Screenshot with unintended behaviors: (delete this line before submitting)
![image](https://user-images.githubusercontent.com/22617255/130504624-f6f6ba5b-568e-4e89-a84b-b25b167c836c.png)

![image](https://user-images.githubusercontent.com/22617255/130504693-582abc4a-6b5e-40ad-9885-6c3a899b5a5a.png)

Screenshots are two different replays of the same TAS, at the same time into the game. The block colors are re-randomized for each replay.

**Comment by Trebor-Huang** [comment]
Probably MrZ forgot to use a dedicated RNG.

**Comment by Trebor-Huang** [comment]
Actually there are already three RNG's that work properly. Using any one of those is fine.
