### ISSUE TITLE
Texts are too long in Romance languages

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#250]
As illustrated in the following images. Texts in these languages are sometimes so long that they exceed the boundaries, overlap with other UI Elements, or go out of the screen.

It is suggested to used a condensed version of typeface or to set different font size for each language to resolve this issue.

![Screenshot 2021-08-28 at 21 46 09](https://user-images.githubusercontent.com/87485746/131220415-9bc6a3a3-c26e-4e9a-bb91-a60e28fbd6cf.jpg)
![Screenshot 2021-08-28 at 21 46 47](https://user-images.githubusercontent.com/87485746/131220419-45212779-e182-4484-8578-61dca36fd242.jpg)
![Screenshot 2021-08-28 at 21 47 13](https://user-images.githubusercontent.com/87485746/131220420-19c9fd24-e28f-4701-aba1-15e64f04f449.jpg)

**Comment by shoucandanghehe** [comment]
I believe that shorter words are preferable, but we do not have any speakers of these languages on our team.
We can make the font smaller, but I don't think it looks good.

**Comment by Trebor-Huang** [comment]
We need either a marquee sort of thing, or ask the translators to cut it short.

**Comment by Trebor-Huang** [comment]
AFAIK most games don't change the fonts, and when they have to, they only squeeze the width without changing the height.

**Comment by C29H25N3O5** [comment]
> AFAIK most games don't change the fonts, and when they have to, they only squeeze the width without changing the height.

AFAIK, some games use different fonts for Latin/Cyrillic scripts and CJK scripts. For example, iOS (though it is a OS rather than a game) and other OS by Apple uses SF Pro for Latin/Cyrillic/Greek scripts, PingFang for Chinese Characters, and Hiragino Sans for Japanese scripts; so I think it is a good idea to use different fonts for Latin scripts and CJK scripts.

Also I think there is some problem with the current typeface (Alibaba Sans/Alibaba PuHuiTi). The Latin letters in this typeface is rather too wide. I think it is better to used condensed fonts.

Here I tried a variety of fonts that are narrower that Alibaba Sans, and I hope this would be helpful:
![Screenshot 2021-08-28 at 23 14 16](https://user-images.githubusercontent.com/87485746/131222817-3689014e-6b4e-4221-9870-5e53a620da49.jpg)

**Comment by C29H25N3O5** [comment]
There. I quickly created these mock-up version of the GUIs in the "Custom Game" mode with different kinds of condensed typefaces:

![Untitled 3 001](https://user-images.githubusercontent.com/87485746/131225003-4961def0-2db9-4ea4-9849-501b2e97cea1.jpeg)
![Untitled 3 002](https://user-images.githubusercontent.com/87485746/131225010-e8464aa8-9f67-4502-9a81-f9ac796219a0.jpeg)
![Untitled 3 003](https://user-images.githubusercontent.com/87485746/131225020-cf478177-3574-4c17-9d68-b59b80844fe4.jpeg)
![Untitled 3 004](https://user-images.githubusercontent.com/87485746/131225023-34ab552d-0849-49e5-8834-9ef61407b3ba.jpeg)
![Untitled 3 005](https://user-images.githubusercontent.com/87485746/131225025-3da2570f-514b-466d-840e-27644c646aeb.jpeg)

I don't know what you think but I think DIN Condensed is a more appealing typeface to me (perhaps the texts are clearer and easier to read?).

**Comment by Trebor-Huang** [comment]
I see what you mean.

Looks fine to me. We just have to come up with a way to use that font, but fall back to the Alibaba one on CJK glyphs. Is there an API for this in love?

**Comment by shoucandanghehe** [comment]
Maybe we can merge the two fonts, but I don’t know if I have the right to do so

**Comment by MrZ626** [comment]
> Looks fine to me. We just have to come up with a way to use that font, but fall back to the Alibaba one on CJK glyphs. Is there an API for this in love?

Yes, I'll try this later

**Comment by user670** [comment]
Hmm

Some condensed fonts look not too nice. If there is a natural-looking font that happens to be narrower, great. (When [Capcom localized Phoenix Wright: Ace Attorney: Dual Destinies into English](https://www.capcom-unity.com/2013/10/17/phoenix-wright-ace-attorney-dual-destinies-localization-the-trials-and-tribulations-of-the-gameplay-mechanics-team/), they custom-made a narrower font, and it looks decent) However if you specifically went out and looked for a "condensed font" like some of the screenshots above, ... some of them I don't like. Specifically DIN is the one I dislike the most from the screenshots, while Founders and Roboto look the nicest to me.

On the other hand, are we (not) going to consider the following two things too?:
- UI re-design,
- automatic font size adjusting

**Comment by Trebor-Huang** [comment]
I agree, an alternative solution is to adjust the UI so as to be more tolerant to different text lengths. We might even have two or three layouts to dynamically choose depending on the text, but that's probably way to hard.

**Comment by MrZ626** [comment]
Now long texts will be squeezed into a safe area
