### ISSUE TITLE
Feature Request: a better way to change the target of attack in Tech 49 & 99

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#267]
Currently in Tech 49 and Tech 99 mode, the method to change your target of attack (Random/Badges/K.O.s/Counter) is to press [fn1] and [move left/move right/hard drop/soft drop] at the same time. 

This is great if you use ← for moving left, → for moving right, ↓ for soft drop, and ↑ for hard drop. However, this becomes a problem when you set [Space] for hard drop and ↑ for rotate right (which I believe many people do). When that is the case, [fn1] + ↑ doesn’t do anything. If you want to change your target to “K.O.s”, you have to press [fn1] + [Space], which I believe is not so convenient. 

In my opinion, there are two ways to solve this problem:
  1. Set another four keys to change the target, or
  2. Use <fn1> + arrow keys to change the target.

**Comment by shoucandanghehe** [comment]
You can turn it off in the settings
![IMG20210830162817](https://user-images.githubusercontent.com/51957264/131310157-65cb81ed-0cb8-43d6-80df-f1a17f9fc0ba.jpg)

and use "Function1" to switch the mode

**Comment by C29H25N3O5** [comment]
Okay. Close this issue.
