### ISSUE TITLE
Add a return button in the console interface

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#270]
Currently one way of entering the game console is the click on the “TECHMINO” logo on the homepage several times. 

On PC and Mac, exiting the console is as easy as pressing the `esc` key. However, the virtual keyboards on mobile devices typically do not have the `esc` button. So on mobile devices, the only way to exit the console is to restart the game.

Therefore, I think it would be much more reasonable to add a return button on the console page itself.

**Comment by MrZ626** [comment]
the way to quit console is designed to be using "quit" command, esc key is just for convenience

**Comment by C29H25N3O5** [comment]
Okay. Issue closed.

**Comment by C29H25N3O5** [comment]
> the way to quit console is designed to be using "quit" command, esc key is just for convenience

If that is the case, how about adding the `quit` command in the output of the `help` command? I think the `quiT` command was not included there.

**Comment by shoucandanghehe** [comment]
In fact, the return gesture of the mobile device can also exit, (iOS does not know)

**Comment by shoucandanghehe** [comment]
There is `exit` command in help, and it can also return
