### ISSUE TITLE
Quit button in simplistic mode on iOS does not close the game

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#273]
When simplistic mode is applied to the homepage layout, there is a quit button (little ×) at the lower right corner of the page. Theoretically, pressing this button should close the game in iOS, but in reality it just restarts the game without actually quitting it (see the video for more):

https://user-images.githubusercontent.com/87485746/131535028-c85191a9-a0ca-47b9-ae21-3044250e25bb.mov

**Comment by Trebor-Huang** [comment]
In iOS, it is impossible to close the app without the user tapping the home button. Calling the quit API *crashes* the app instead of quitting it. This is a deliberate design choice by apple, and the löve engine restarts when `quit()` is called.

So, maybe we just hide that button on iOS :P

**Comment by C29H25N3O5** [comment]
> So, maybe we just hide that button on iOS :P

Yeah, that would be much better.
