### ISSUE TITLE
The attack mode is not displayed for multiplayer modes on iOS

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#275]
Usually the way to change the target of attacks using keyboard in Tech 49 & 99 is to press `fn1` + `some specified keys`.

It does work on iOS, except that the target cannot be displayed on the field even if I turn on “Key Combination (Attack Mode)” in Settings (See the images for details):
![Tech 49 EASY](https://user-images.githubusercontent.com/87485746/131613518-3e942083-07e8-4931-9b63-2659decf59fa.png)
![Control Settings](https://user-images.githubusercontent.com/87485746/131613533-ba547d91-f184-47c4-a2a7-6ae48939777f.png)

**Comment by MrZ626** [comment]
Coordinate of players is changed in 0.16.0 and i didn't notice this bug
It was fixed weeks ago

**Comment by C29H25N3O5** [comment]
> Coordinate of players is changed in 0.16.0 and i didn't notice this bug
> It was fixed weeks ago

Also notice that the latest build of Techmino on iOS is 0.16.0 instead of 0.16.1.

**Comment by shoucandanghehe** [comment]
> Also notice that the latest build of Techmino on iOS is 0.16.0 instead of 0.16.1.

ios is currently not automated
and we lack ios developers (
