### ISSUE TITLE
Voice pack concerns

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#288]
Sorry for merging 3 things into one issue

- Can we make the game not complain about the many missing voice clips for pentomino spins every time a voice pack is loaded?
- Miku lacks a win voice
- Also Miku's B2B can have a few dozen milliseconds of silence at the end, now it feels rushed when combined with another clip
- What's the license agreement for (the voice of) Miku? Are we entitled to use it in our game? (Do note that Techmino **does make profits** via donations)

**Comment by MrZ626** [comment]
1.yes
2.i'll ask the author of voice pack
3.yes, i'll edit it later
4.i think it's not a big problem, you know that
