### ISSUE TITLE
Feature Request: Add a mod that force to display the ghost piece

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#289]
As in the title. this would be useful in modes where ghost pieces are invisible by default (CTWC etc.).

**Comment by C29H25N3O5** [comment]
This issue should be reopened as the latest commit (`a021fcd`) re-introduced this issue again.

**Comment by MrZ626** [comment]
https://github.com/26F-Studio/Techmino/projects/2#card-68593837
the whole mod system will be remade, so it's better to add a card here (idk if permission needed)
