### ISSUE TITLE
Endless marathon mode

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#297]
Consider adding an Infinite Marathon as with each level going up the speed increases and the lock delay decreases and we rank the player by score. The game is over when the player tops off.

However, I think there are two options available when dealing with the levels:

1. By lines (as in TOP and tetris.com). Each time when 10 lines are cleared, the game goes to the next level.\
2. By attack (ad in EA Tetris [No longer available]). There is a goal of attack in each level, and with each level going up, the goals also become higher.

A reasonable setting would be something like this:

| __Level__ | 1    | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    | 10   | 11   | 12   | 13   | 14   | 15   | ... |
| --------- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| __Goal__  | 5    | 10   | 15   | 25   | 35   | 50   | 65   | 85   | 105  | 130  | 155  | 185  | 205  | 240  | 275  | ... |

**Comment by user670** [comment]
The 2: It's not attack, more like "multiple-of-100-score". Single/Double/Triple/Tetris is +1/3/5/8, for example. Also, that type of Marathon has became very unpopular in official games; new games almost never use this type of Marathon, and when Tetris Journey had it in a very old beta, the players generally disliked it.

**Comment by MrZ626** [comment]
> I can make this mode, so should I do it or not?

Mind changed, a smooth, well-balanced, not simply combination of other marathon/master modes, is appreciated. Remeber don't make it too long, or it will be boring. My suggestion is 1000 lines at maxium, optional bonus life, like 1(2) bonus life(lives) at 500 (400, 700) lines.

**Comment by user670** [comment]
The only reasonable end condition for an endless marathon is to top out. If you have an artificial end point like 1000 lines, it's not endless. (But you *can* re-brand this 1000-line thing "endurance mode" or something)

But on the other hand - true endless marathon would be infinite sandbox but faster, and 1000-line marathon would be 1000-line sprint but faster. If you don't care about this, I'm fine with that; otherwise you might want to consider how to make the "endless marathon" different from these other modes?

**Comment by user670** [comment]
Or you can do it Tetris.com-style and extend the speed curve beyond Lv20, and be like play until you die

**Comment by user670** [comment]
> Tetris.com stops at lvl30

Yes it does, if you want endless just decrease the delays more for Lv31 until it takes a single frame to lock and totally humanly unplayable. Or until it takes 0 frames to lock and be TAS-unplayable too

**Comment by MrZ626** [comment]
Oh wait, I mean, not endless with capped-speed
lock delay should be shorter and shorter until humanly unplayable

**Comment by MrZ626** [comment]
Real "infinite marathon" is so boring, isn't it
