### ISSUE TITLE
7-Bag system experience some glitches from time to time.

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#301]
Specifically, sometimes the generator produces 2 identical tetriminos in the initial bag. This phenomenon does not occur very often, but this is a real problem.

More on the following video. In this example 2 J-minos was generated and the S-mino was lost.

https://user-images.githubusercontent.com/87485746/133541497-80aff14f-7967-426e-ad72-9b17dbe8cff3.mov

**Comment by MrZ626** [comment]
Marathon and master modes have "no Initial SZO" tag
