### ISSUE TITLE
Feature request: NoInitSZO keeps first bag intact

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#303]
#301 and #172 find NoInitSZO messes up their first bag, which can cause trouble if they are doing a 7-bag-dependent opener. Request that when using a bag randomizer and NoInitSZO=true, keep the bag intact, for example by moving the SZO to later in the bag instead of deleting them.

**Comment by MrZ626** [comment]
This is not a easy thing, noInitSZO should use same simply ways to remove initial SZOs, so I have to break the first bag...

**Comment by MrZ626** [comment]
It's an obvious solution, but it only works when bag+normal pieces

**Comment by user670** [comment]
> It's an obvious solution, but it only works when bag+normal pieces

what do you mean by "bag+normal pieces"?

also I specifically said I want the first bag intact **when using bag randomizer**

**Comment by MrZ626** [comment]
I want to make noInitSZO rule effecting all sequence modes with single algorithm.
But it seems... impossible? 
So this issue should be closed if there isn't a way, I think.

**Comment by user670** [comment]
What are your objectives/restrictions here? What can the noInitSZO algorithm know about (i.e. what are the inputs)? Must it not know what randomizer is being used?

btw bag is literally the only randomizer that calls for this special treatment.

**Comment by user670** [comment]
There is a potential algorithm that theoritically works without needing prior knowledge but may break some properties of some randomizers.

The algorithm: if first piece is SZO, find the first piece that isn't SZO, then swap that with the first piece. eg:
```
SZOITLJ
^  ^ swap these two
IZOSTLJ
```
It **will** cause bags to come in different probabilities in bag algorithm (bags whose 2nd piece is SZO is more likely to appear than a fair randomizer).
It **will** break the echo randomizer (eg "SSSSTTTT" will become "TSSSSTTT", violating the regular rules of that randomizer.)
Not sure what other problems it will bring.

**Comment by MrZ626** [comment]
Adding a new randomizer (may called "bag_noInitSZO") is better, later I'll remove the noInitSZO thing
