### ISSUE TITLE
crash on clicking classic mode

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#308]
![Screenshot_20210921_022308_org love2d MrZ Techmino Snapshot](https://user-images.githubusercontent.com/22617255/134054325-a79b4b92-822c-433c-8798-5c10f6e49526.jpg)

when I click on the classic mode directly after the marathon mode (with the classic mode in question being locked), it crashes

Android 8 (I think), Huawei P30 Pro

**Comment by MrZ626** [comment]
@Not-A-Normal-Robot forgot to change all language files of classic modes, I'm working on these.

**Comment by MrZ626** [comment]
(And rebalancing them)
