### ISSUE TITLE
Feature Request: Update the App Icon on macOS to fit with the system-wide designing 

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#319]
On macOS Big Sur, the icons of the built-in Apps were redesigned into rounded rectangles with shadow.

To fit with the system-wide icon redesign, most Apps on macOS now uses similar designs (rounded rectangle with shadows). However, on macOS, the icon of Techmino still appears to be a big square (and unlike iOS and iPadOS, macOS does not automatically cuts off the extra portion outside the rounded rectangle):

It is highly recommended that Techmino should follow the same designing language into the icon of the App:

<img width="383" alt="Screen Shot 2021-09-22 at 5 25 26 PM" src="https://user-images.githubusercontent.com/87485746/134430156-7fe9f478-def8-424b-8cad-13aa6519526a.png">

More information can be found [here](https://developer.apple.com/tutorials/mac-catalyst/updating-the-app-icon/).

**Comment by Trebor-Huang** [comment]
Whassat
Oh alright I'll do it
