### ISSUE TITLE
Keyboard navigation of menus is broken

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#329]
Settings -> Video -> line no. can't be reached purely using a keyboard

also it's janky in general, why does pressing right sometimes selects the element above or below

**Comment by MrZ626** [comment]
Actually not impossible, you need adjust other slider to some position as a spring board to reach the line no. slider lol

**Comment by MrZ626** [comment]
2. Because when you press right, game will search all widgets and find "the closest one", distance calculating allows this. I cannot find a better algorithm to do this

**Comment by user670** [comment]
So wait, the "position" of a slider is not the entire object but the knob? what??? hmmmmmm

**Comment by MrZ626** [comment]
> So wait, the "position" of a slider is not the entire object but the knob? what??? hmmmmmm

there is two position concept for each widget, one for "move to me" position (can contain many points), another one for "move to others", only have one point. For slider, the former one is the position of its knob.

**Comment by MrZ626** [comment]
The question is, how to make a better keyboard navigation of menus?

**Comment by MrZ626** [comment]
combined with #479
