### ISSUE TITLE
Switch voc/sfx packs at the launchpad

### ISSUE THREAD

**Issue by Trebor-Huang** [26F-Studio/Techmino#336]

**Comment by MrZ626** [comment]
Now the voc/sfx module is designed to not change pack so often, there is only one pack loaded at the same time.
The game will lag for about 0.* second to load sound files.

**Comment by Trebor-Huang** [comment]
Nitpick Proofreading: **A fraction of a second** is a good English expression for that.

**Comment by MrZ626** [comment]
> Maybe make changing pack in another thread so that the draw thread doesn't get stopped?

The real problem is you cannot switch sfx/voc packs immediately, multi-threading doesn't solve this.

**Comment by MrZ626** [comment]
I thought again and realized **this launchpad** shouldn't have this function.
It's unrealistic, for there will be more and more sfx/voc packs in the future.

**Comment by Trebor-Huang** [comment]
> I thought again and realized **this launchpad** shouldn't have this function. It's unrealistic, for there will be more and more sfx/voc packs in the future.

To be honest I find this unintelligible.

**Comment by MrZ626** [comment]
> > I thought again and realized **this launchpad** shouldn't have this function. It's unrealistic, for there will be more and more sfx/voc packs in the future.
> 
> To be honest I find this unintelligible.

Unnecessary & Impossible
