### ISSUE TITLE
Code-sign the macOS distribution of the App

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#339]
When opening Techmino for macOS for the first time, the following window pops up:

<img width="372" alt="Screenshot 2021-09-27 at 15 27 02" src="https://user-images.githubusercontent.com/87485746/134985469-8b3715fb-0a19-4164-8871-778c654cc4cf.png">

To open the App, you must first go to System Preferences > Security And Privacy > Allow Apps Download from: “Anywhere” to grant access to the App.

Then, you have to right-click (or Control-click) the App and select “Open” from the menu to actually open the App:

<img width="328" alt="Screenshot 2021-09-27 at 15 27 28" src="https://user-images.githubusercontent.com/87485746/134985511-50365b53-ec29-4ee0-b069-64eb231f3c6e.png">

For first-time users, it is really inconvenient and many of them don’t really know this process. As a result, they cannot open the App at all.

It is highly recommended to code sign the macOS distro of the App to resolve this issue. More information [here](https://developer.apple.com/support/code-signing/).

**Comment by Trebor-Huang** [comment]
To do this we need to build instead of modify.

**Comment by Trebor-Huang** [comment]
I think what you want is nortarizing. This requires rebuiding the whole love app, instead of modifying it.

**Comment by Trebor-Huang** [comment]
Oh wait you don't need hardened runtime now. But you still need to send the app to Apple to have it notarized.

**Comment by MrZ626** [comment]
Moved to https://github.com/26F-Studio/Techmino/projects/2#column-11869087
