### ISSUE TITLE
Apple Developer ID, and all that jazz

### ISSUE THREAD

**Issue by Trebor-Huang** [26F-Studio/Techmino#341]
Issues like #339 and build/release-automation is calling for an official Developer ID for Techmino (or 26F Studio).
**Pros**:
- We get to release iOS builds without having to bother someone every time.
- We get to codesign and notarize MacOS apps.
- We get (the chance) to release App Store apps.

**Cons**:
- We need to pay $99 per year.

**Comment by MrZ626** [comment]
Waiting for ci first

**Comment by C29H25N3O5** [comment]
BTW id you want to distribute your app to iOS and macOS via App Store, you have to remove the QR Code on the about page. Apple does not allow third-party payment methods. You have to use Apple’s API in order to do that.

**Comment by MrZ626** [comment]
Moved to https://github.com/26F-Studio/Techmino/projects/2#column-11869087

**Comment by Trebor-Huang** [comment]
ci is prepared @MrZ626
