### ISSUE TITLE
Problems about the backward compatibility of exported statistical data

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#346]
It is literally impossible to import data about your statistics from an earlier version (0.16.1) to a later version (0.16.2 Dev). 

By the way, the 0.16.2 (Dev) can import the other three kinds of data (progress, settings, virtual key layouts) without any problem. But cannot import statistical data. Every time I try to do it the game prompts “Data corrupted”. 

See the video for more:

https://user-images.githubusercontent.com/87485746/135286205-cc539258-f9f6-4e00-9fa3-ddc6cf2201a5.mp4

**Comment by MrZ626** [comment]
You can only export/import statistics in the same version, or weird things will happen
I didn't write it down so players won't know this

**Comment by C29H25N3O5** [comment]
\[low priority\] \[dispute\] \[enhancement\]

**Comment by Trebor-Huang** [comment]
The semantic versioning doesn't enforce any sort of backward-compatibility before 1.0. So I guess you probably won't get it :(
