### ISSUE TITLE
Help file not included in macOS distro

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#347]
It seems that the latest commit by @Trebor-Huang didn’t included the file in the macOS distro.

**Comment by Trebor-Huang** [comment]
What, why?
We don't need the help file in snapshot builds, right?

**Comment by C29H25N3O5** [comment]
OK just remember to include it on Stable Build. Issue Closed.

**Comment by C29H25N3O5** [comment]
BTW I just forgot that this is the snapshot rather than the Stable Build…

**Comment by Trebor-Huang** [comment]
Done.
