### ISSUE TITLE
Use monospaced font for in-game console (multi-fonts in game)

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#349]
Conventionally, the standard font displayed in the command-line interface is monospaced. This is because monospaced fonts have very high readability (especially in smaller font) sizes, and users can tell the difference between similar characters (`I,l,1,|`) easily.

It is highly recommended to apply a monospaced font to the in-game console in Techmino. (Currently, all the UI elements use Alibaba Sans for the standard font.)

**Comment by C29H25N3O5** [comment]
I think JetBrains Mono is better because it has higher readability on smaller font sizes.

<img width="653" alt="Screenshot 2021-09-29 at 18 41 10" src="https://user-images.githubusercontent.com/87485746/135363057-d3e0f3a3-77f4-4fdc-8167-cf88bd901ee5.png">

**Comment by C29H25N3O5** [comment]
SF Mono also has a clean look, but it is the proprietory font of Apple, so we can’t use it...

**Comment by MrZ626** [comment]
FONT module should support switching fonts first
