### ISSUE TITLE
`/` and `\` are not rendered properly in new font

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#363]
They are not rendered properly at least in Ubuntu 20.04 LTS.

**Comment by ImpleLee** [comment]
It is only problematic after commit e4d62cc4

**Comment by MrZ626** [comment]
Fixed three times but still lack some characters lol

**Comment by C29H25N3O5** [comment]
I will try to fix this issue later (apparently I forgot to included some characters in Glyphs). 

Also there is some minor issues with the baseline of the font and I am going to fix that too.

**Comment by C29H25N3O5** [comment]
Fixed in Pull Request #364. Please merge it ASAP and close this issue.

**Comment by C29H25N3O5** [comment]
@ImpleLee This issue is now fixed.
