### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/Techmino#393]
There is currently no release procedure in Techmino, so we can see MrZ's rushed commits just before a new version, which could, and also did, result in untested buggy releases and urgent needs for immediate new bug fixes that are again highly likely to be buggy and need some more bug fixes, after which MrZ would finally realize the necessity of testing, but makes the same mistake in next release...

We need release procedure to ensure new releases are tested and bug-free, or even change the impression of release candidates in the community.

Some useful points:
- make a release branch at least 3 days before every new release.
- releases can be made only if there has been no bug found for at least 3 days after the latest bug fix applies.
- no new commits should be added to the release branch -- only fixes for new bugs that are found after the release branch is made.

**Comment by MrZ626** [comment]
\*Transferred to the github wiki page*
