### ISSUE TITLE
Feature request: display Chinese pubctuation as Chinese punctuation

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino#400]
re commit 8d0780cef44a69bcdedc5d46b228513c5099af99

You do realize that this game **will display player-inputted text**, right? (like chat and room names) I don't want my Chinese punctuations in my chat messages be displayed as half width by your font.

**Comment by C29H25N3O5** [comment]
当然如果你想要我也可以根据[这个视频](https://www.bilibili.com/video/BV1Lr4y127qp?spm_id_from=333.999.0.0)做.

直接加个 OpenType Feaure 就行. (calt)

For an advanced CJK punctuation guide, take a look at [this video](https://www.bilibili.com/video/BV1Lr4y127qp?spm_id_from=333.999.0.0) (in Simplified Chinese).

This could be realised by adding some OpenType Features.

**Comment by user670** [comment]
I guess it's much better, at least the full stop is now properly a circle instead of a dot.

Also may I be enlightened with why you want a more compact format (with some punctuation still half-width)? Is screen space a big issue with Chinese text in the game?

**Comment by C29H25N3O5** [comment]
Also, the Kaiming Style is used in many official documents, technical papers, dissertations, books, and even exam papers.

In addition, Adobe InDesign lets you change the spacing between those punctuations even more flexibly, but in the game this is realised by the `dlig` OpenType feature.
