### ISSUE TITLE
Switching to love 11.4

### ISSUE THREAD

**Issue by Trebor-Huang** [26F-Studio/Techmino#405]
I'm writing from the perspective of macOS builds.
It solves #352 #339 #345 and so on. It *claims* to solve the @rpath problem, but as far as I've tested it doesn't.

This needs discussion, especially on the pros and cons when considering cross-platform performances.

**Comment by ParticleG** [comment]
I think we could just wait for 12.0

**Comment by shoucandanghehe** [comment]
#732 seems to be already building new `dev` version with `love11.4`. (with some minor issues)
But only `dev`(
At the same time this pr removes some things needed for `release` and `test`, so these two actions should also be migrated as soon as possible

**Comment by ParticleG** [comment]
Now fully migrated to 11.4 with new CI
