### ISSUE TITLE
[legals.md not found]

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#430]
Screenshot with unintended behaviors: (delete this line before submitting)

![](https://cdn.discordapp.com/attachments/703979930983071815/906127749117251594/unknown.png)

If you can reproduce it, write the steps here. If you can't, try to describe the exactly time the game crash, like pressing which key or which button: (delete this line before submitting)
*Details Here*

(screenshot from not a robot, win10. I got that on android too.)

**Comment by C29H25N3O5** [comment]
Also for iOS and macOS.

It is strange that when I drag the folder onto the love.app the `legal.md` is properly displayed. but when running the compiled application, this problem occurs on all platforms. 

I have talked about this issue with @MrZ626 and he said this problem can be solved by changing the format of this file from Markdown to Lua. There is some mysterious error that caused this file to not be included in the build.

**Comment by MrZ626** [comment]
Oh I think I found the reason
