### ISSUE TITLE
Problems with “Copy” function in Zictionary

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#442]
1. Go to Zictionary
2. Go ahead to any entry that contains “ᴛᴇᴛʀɪs” (replaced by a “Thinking Z” emoji)
3. Hit the “Copy” button on the page
4. Paste it anywhere
5. Realise that the “Thinking Z” emoji is a glyph from Private Use Area in Unicode and it can’t be displayed properly if the in-game font is not installed on the device

![IMG_5248](https://user-images.githubusercontent.com/87485746/141005587-91da5051-57f9-434c-b0fa-9bca285a4f49.jpg)

**Comment by user670** [comment]
So... what should the :thinkZ: be in the copied text? Revert to `Tetris`? Use something else like `[Censored]`?
