### ISSUE TITLE
添加局域网功能

### ISSUE THREAD

**Issue by paoho** [26F-Studio/Techmino#446]
因为网络不太稳定，总是会玩着玩着掉线，而且注册也比较麻烦，能否添加局域网功能？

**Comment by MrZ626** [comment]
很难。相当于客户端要内置一个服务端

**Comment by ParticleG** [comment]
客户端很难实现，因为涉及多平台开服问题，但是未来[新的服务器](https://github.com/26F-Studio/Techluster)会提供一键部署对战节点的方法，可以在本地建立子节点并和总网关通信
