### ISSUE TITLE
Random BGMs don’t play on iOS

### ISSUE THREAD

**Issue by andrew4043** [26F-Studio/Techmino#447]
Screenshot with unintended behaviors: 
[Youtube link to the bug](https://youtu.be/zxSAePVbfGU)
![image](https://user-images.githubusercontent.com/20546331/141156302-d1fdcf74-4346-4bba-98a4-809250379967.png)

Reproducible, but randomly; trying to play all BGMs usually results in this bug happening. iOS 14.8, iPhone 12 mini

**Comment by MrZ626** [comment]
can you test this:
1.turn all volumes off, only keep Main and BGM on
2.count how many musics played before this bug happen

**Comment by andrew4043** [comment]
here's what I got:
going up from "nil", everything works except "8-bit happiness"
going back to "nil" from the SFX menu and going down, "null", "overzero", and actually everything below that stops playing
going back and playing "nil" still works.


OH and I forgot to put the version number, v0.16.4 Wormhole

**Comment by MrZ626** [comment]
wait, I forgot SFXs and voices should also be counted
what voice pack did you choose?

**Comment by C29H25N3O5** [comment]
This issue also happen to me (iPhone 12 Pro, iOS 15.0)

**Comment by MrZ626** [comment]
reason found, love2d can load maximum 255 sound files at the same time on iOS
