### ISSUE TITLE
Empty doesn't loop

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#448]
https://github.com/26F-Studio/Techmino/blob/8c7202c5692aa6448fec0c7fa336361e4691acf4/media/music/empty.ogg

This song doesn't loop properly (can fix by cutting off a bit of the silence at the end of the song, aligning to the beat)

**Comment by MrZ626** [comment]
I think this song don't need to be perfectly looped, since its starting/ending don't have many kicks/snares

**Comment by MrZ626** [comment]
@user670

**Comment by MrZ626** [comment]
if it's totally not necessary, this will only make repository 1M larger

**Comment by user670** [comment]
> You can resolve this issue by cutting out the silence at the end of the bgm... I don't see how cutting a part of the music can increase its size

Git keeps all historical versions of all files. It doesn't increase the size of the game, but it does increase the size of the ***repository***.

**Comment by Gompyn** [comment]
If you do not need all versions, you can use `--depth N` when cloning (specially, use `--depth 1` for shallow clone); if you do need all versions, 1MB is little compared to the size of the repo which is `178.11 MiB` (less than `0.7%`), or even the size of a shallow clone which is `58.69 MiB` (less than `1%`).

**Comment by ImpleLee** [comment]
1MB is little compared to the size of the repo (`178.11 MiB`) or even the size of a shallow, depth-1 clone (`58.69 MiB`).
If you don't need the history of the repo, you can clone with `--depth N` (specially, use `--depth 1` for a shallow clone).

**Comment by shoucandanghehe** [comment]
This issue should now be fixed by 09d3202
