### ISSUE TITLE
An English Translation for a Button is Missing

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#467]
<img width="1680" alt="Screenshot 2021-11-17 at 15 18 22" src="https://user-images.githubusercontent.com/87485746/142294218-f616f66c-6aa6-4c9b-b428-51ac066c8832.png">

Should we call it “Hold Mode” or “Hold Behaviour”?
(this menu is supposed to used to change the behaviour of the hold button \[Hold or Swap\])

**Comment by C29H25N3O5** [comment]
> Hold Mode is simpler, we should use that.

Okay, that makes sense.

**Comment by MrZ626** [comment]
fixed half of it lol
