### ISSUE TITLE
Is this thing in the logo intentional??

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#485]
![image](https://user-images.githubusercontent.com/22617255/143149387-9d7bb41a-b659-4f0b-a2d6-b40ba81b0307.png)
This only happens with the main menu version of the logo (the one you tap 4 times to go to console). (edit: credits screen too) The loading screen one is fine (somehow).

**Comment by MrZ626** [comment]
don't know why, all logo use the same data but only loading screen one is correct
