### ISSUE TITLE
Timer of ultra mode sometimes doesn‘t count exactly to 2 mins

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#486]
<img width="1680" alt="Screenshot 2021-11-24 at 01 02 27" src="https://user-images.githubusercontent.com/87485746/143190602-225eab99-aaee-43d0-8a35-d2217e4e2bbb.png">

May becomes 1’59.99” or 1’59.94” or some other random times. Happens occasionally.

**Comment by MrZ626** [comment]
Actually not bug, time and frame not always match

**Comment by C29H25N3O5** [comment]
Actually I think a countdown is more reasonable

**Comment by MrZ626** [comment]
Using a timer instead of time bar?

**Comment by C29H25N3O5** [comment]
Well in my view a countdown is more intuitive than a time bar because it allows players to see exactly how much time they have

**Comment by MrZ626** [comment]
if you turn off the `Frame skip` setting and your device is not fast enough, this time can be much bigger, like 130s.
So I think it's not a bug
