### ISSUE TITLE
Commit be54c0e641120124b1289924bd9dc62f7af0d402 doesn't respect old background settings

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#496]
Screenshot with unintended behaviors (*Image(s) Here*):

If you can reproduce it, write the steps here. If you can't, try to describe the exactly time the game crash, like pressing which key or which button (*Details Here*):
- Play a version pre-commit be54c0e641120124b1289924bd9dc62f7af0d402 , and **set background to disabled**
- play a version post-commit be54c0e641120124b1289924bd9dc62f7af0d402
- now background is enabled, despite previous settings

**Comment by user670** [comment]
Also, new version's default 26% background alpha makes it more white than the previous no background? What was the old value? Set that as default please?

**Comment by MrZ626** [comment]
~~Care too much~~
Players will adjust them again and find there is new feature.
I think it's not bad

**Comment by MrZ626** [comment]
old `no background` is 8%
