### ISSUE TITLE
Monospaced font uses Japanese character shapes for CJK characters?

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#498]
Screenshot with unintended behaviors (*Image(s) Here*):
![image](https://user-images.githubusercontent.com/22617255/143727018-6345d6bf-635f-4310-bb1c-bcc8b1cbc3ce.png)

If you can reproduce it, write the steps here. If you can't, try to describe the exactly time the game crash, like pressing which key or which button (*Details Here*):
- Have the game somehow display some CJK characters in monospace font, eg. by typing them into console
- Observe that the characters are in Japanese shape

For reference, this is the same characters in a Chinese font (in Chinese shape):
![image](https://user-images.githubusercontent.com/22617255/143727097-e6670599-7dc3-4c63-bba5-096972429b67.png)

**Comment by MrZ626** [comment]
@C29H25N3O5
