### ISSUE TITLE
[console] In sudo mode, #print doesn't print to the on-screen "console"

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#499]
Screenshot with unintended behaviors (*Image(s) Here*):
![image](https://user-images.githubusercontent.com/22617255/143727153-10b47932-0d7a-44f4-af96-ae414dcf5904.png)

If you can reproduce it, write the steps here. If you can't, try to describe the exactly time the game crash, like pressing which key or which button (*Details Here*):
- As shown above

Probably because the user environment for sudo mode doesn't overwrite the print function and it tries to do the vanilla Lua print function and prints to the actual terminal window (yes bringing up the actual terminal window with debug mode then doing #print will show the printed content in the terminal)

**Comment by MrZ626** [comment]
In sudo mode, you are using the environment of the whole game, `print` is a lua function so better not to change it. Normal #print is just share the `print` function name, not the same thing.
I have no idea about this.

**Comment by user670** [comment]
If you insist on not changing the print function, what's a function that can put text on the in-game console? Mention that either in-game or in GitHub?
