### ISSUE TITLE
Fallback disabled keys to an available key

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#500]
![image](https://user-images.githubusercontent.com/22617255/143729061-0d435ed3-7965-49a6-a8dc-2b2dd831fd2d.png)

![image](https://user-images.githubusercontent.com/22617255/143729226-55feb2ce-97df-46f3-a43a-53c9ed7a8660.png)

This is to solve #258

**Comment by MrZ626** [comment]
Feel extremly unneccessary
