### ISSUE TITLE
Question: what is wrong with my Last Played?

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#510]
![Screenshot_20211130_001432_org love2d MrZ Techmino Snapshot](https://user-images.githubusercontent.com/22617255/143903364-867f6837-e9f6-4536-8a2b-a9630301cc64.jpg)

Maybe I last played a now-deleted mode from an old version that had that mode? (Is it a bug?)

**Comment by C29H25N3O5** [comment]
In fact, this issue has been there for quite a long time. Also…
<img width="1680" alt="Screenshot 2021-11-29 at 10 17 52" src="https://user-images.githubusercontent.com/87485746/143903890-05ec1601-42c0-4bf0-a5c7-ba0cfc89251b.png">

**Comment by Trebor-Huang** [comment]
This is presumably intended.
