### ISSUE TITLE
New level selection UI

### ISSUE THREAD

**Issue by C29H25N3O5** [26F-Studio/Techmino#541]
This is not really an issue but more like a reminder. 

- [x] New layout for level selection (File explorer)
- [x] Hierarchies for all levels
- [ ] New icons for level selection
   - [ ] Folders
   - [x] Sprint
   - [ ] Dig
   - [ ] Marathon/20G
   - [ ] Battle
   - [x] Turn-based
   - [ ] Tech 49/99
   - [ ] Invisible
   - [ ] Classic
   - [ ] Survival
   - [ ] Training
   - [ ] PC
   - [ ] Tech-exclusives
   - [ ] TSD
   - [ ] Backfire
   - [ ] Endless
   - [ ] Drought

**Comment by C29H25N3O5** [comment]
> Will this remove the map? I really like the map and I don't want it to disappear

Very unfortunately, MrZ has confirmed that the map will be replaced with a new "file-explorer" like UI. 

Actually MrZ wrote "replace map layout" in the todo list for a long time. He said that he didn't changed it because he could not find a better layout. 

However, MrZ did decide to change the layout and replace all the mode icons in recent updates. I know lots of people like the map but it is his decision to remove it.

**Comment by user670** [comment]
![Uploading IMG20211216092801.jpg…]()

**Comment by C29H25N3O5** [comment]
Just see the `test-new-mode-system` branch for more.

**Comment by C29H25N3O5** [comment]
Seems the map is retained in this game. Closing the issue now.
