### ISSUE TITLE
Text too long causing it to exceed the text box

### ISSUE THREAD

**Issue by AlphaIru** [26F-Studio/Techmino#607]
Screenshot with unintended behaviors (*Image(s) Here*):
![image](https://user-images.githubusercontent.com/51223488/150059566-fdf3072d-cfc1-4e5f-9448-7844a06d4290.png)
![image](https://user-images.githubusercontent.com/51223488/150059445-7578b3ef-e549-4cc3-b774-341be8c1ad23.png)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
Set to Japanese and find the words or conditions that has a long words.

**Comment by AlphaIru** [comment]
Gotcha, sorry for overreacting.

**Comment by MrZ626** [comment]
case 1 is expected,
case 2 is hard to solve, my suggestion is shorten the text

**Comment by C29H25N3O5** [comment]
In fact, I mentioned this issue a long, long time ago in #250
That was the first issue I opened in this repo actually

**Comment by C29H25N3O5** [comment]
A reasonable solution would be to truncate the texts if it gets too long and add an ellipsis at the end of the text strings.

but I know it would involve getting the physical lengths of the texts and kerning stuff and other mumbo jumbos that might make it hard to implement (at least in terms of MrZ's perspective).
