### ISSUE TITLE
Re-translate manual_en/manual_ja

### ISSUE THREAD

**Issue by MrZ626** [26F-Studio/Techmino#613]
I rewrote the `attack system` and `B2B gauge` sections
- [x] en
- [x] ja @AlphaIru

**Comment by AlphaIru** [comment]
All right, I will check it out

**Comment by AlphaIru** [comment]
Sorry, I need to send my pull request so I can update with the newest context from here
.

**Comment by ImpleLee** [comment]
Isn't this fixed by #692 ?
