### ISSUE TITLE
Make Deb, Tar.Gz for Icons

### ISSUE THREAD

**Issue by AlphaIru** [26F-Studio/Techmino#634]
When I tried using .appimage in my Ubuntu. It worked fine, but I hated the fact you cannot: 1, hide files; 2, show up in app list; 3, the appimage icon is ugly. Would you mind creating a deb/targz files so we can customize the game more? (I don't care if this is for stable versions).

**Comment by ImpleLee** [comment]
There seems to be some improvement in löve 11.4 (see [Game Distribution](https://love2d.org/wiki/Game_Distribution)), so I would recommend to wait for update after migration of 11.4.
But generally .deb or .tar.gz files can be created, so I would say I am welcome to a pull request that addresses the issue.
To start, you need to refer to [Game Distribution](https://love2d.org/wiki/Game_Distribution) and change [.github/actions/build-linux/action.yml](https://github.com/26F-Studio/Techmino/blob/main/.github/actions/build-linux/action.yml).

**Comment by shoucandanghehe** [comment]
I will try make .tar.gz.  By the way, there is an icon file inside the appimage, but it doesn't seem to be displayed)

**Comment by C29H25N3O5** [comment]
Really want AppImage for ARM Linux tho

**Comment by shoucandanghehe** [comment]
Some news: the new ci is being produced by ParticleG, I'm not sure what his plans are and whether he would like others to be involved in the production (

**Comment by Gompyn** [comment]
> Really want AppImage for ARM Linux tho

But upstream appimage doesn't support ARM Linux... Maybe ask them to support that?

**Comment by ParticleG** [comment]
> When I tried using .appimage in my Ubuntu. It worked fine, but I hated the fact you cannot: 1, hide files; 2, show up in app list; 3, the appimage icon is ugly. Would you mind creating a deb/targz files so we can customize the game more? (I don't care if this is for stable versions).

Try use this for icons: https://github.com/Alexsussa/AIDM

**Comment by ParticleG** [comment]
> Some news: the new ci is being produced by ParticleG, I'm not sure what his plans are and whether he would like others to be involved in the production (

Of course. The new CI for Linux is moved to [love-actions-linux](https://github.com/love-actions/love-actions-linux). And I couldn't find any solution to the icon issue on Ubuntu. Please help if you could create a workflow for building .deb packages.

**Comment by ParticleG** [comment]
Okay now we have `.deb` packages for linux, and make AppImage's dock icon working. Tested on Ubuntu with XFCE 4 desktop environment. GNOME desktop seems not support dock icon, should be an upstream issue
