### ISSUE TITLE
Character error in Japanese

### ISSUE THREAD

**Issue by aoyuka102** [26F-Studio/Techmino#664]
Screenshot with unintended behaviors (*Image(s) Here*):
![Screenshot_20220304-164134](https://user-images.githubusercontent.com/49553541/156720961-65357419-dc5d-4032-9992-58400642a4e9.jpg)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
When Japanese is selected as a app language, some characters in Zictionary aren't displayed properly. I'm playing on my android phone and I don't know if it happens on PC.

Also, I'm interested in making translation from English to Japanese! I have C1 skill of English and some experiences of game translating.

Thank you!

**Comment by C29H25N3O5** [comment]
OK I forgot to include some Japanese-specific characters. Will be fixed though.

**Comment by ImpleLee** [comment]
Can we add a CI test to ensure every character in parts/language can be rendered? Or is there such tool? @C29H25N3O5

**Comment by ImpleLee** [comment]
Why is this related to REMAKE? @C29H25N3O5

**Comment by MrZ626** [comment]
relate to some font module issue

**Comment by ImpleLee** [comment]
Isn't this issue already fixed?
