### ISSUE TITLE
Local wifi multiplayer request + more

### ISSUE THREAD

**Issue by A7pr8** [26F-Studio/Techmino#676]
### What feature do you want to suggest to the game?
-Please add the ability to play multiplayer by wifi hotspot it will make the game 10 times better
-add game modes to the game bcz solo is a bit complicated
 like:marathoon with 100 line and the level gets higher the more u advance
-freeze like the one in tetris effect as a new game mode
-analog istead of buttons for moving pieces for touchscreen controls
-better voices (—_—)

Other than that I think the game is perfect

**Comment by C29H25N3O5** [comment]
Please separate this issue into some smaller issues. Thanks.

**Comment by C29H25N3O5** [comment]
Also, MrZ once said this is hard and he doesn’t really want to implement this

**Comment by MrZ626** [comment]
I thought about most of these:
1. wifi-multiplayer is hard
2. coming soon
3. coming soon
4. coming soon
5. coming soon
