### ISSUE TITLE
Removing garbage by clearing more lines than the height allows 

### ISSUE THREAD

**Issue by pChochura** [26F-Studio/Techmino#684]
### What feature do you want to suggest to the game?

In the "stack_e" mode there's a possibility to clear more lines than the maximum board height (it is called Impossicrash). It would be great if this resulted in removing as many garbage lines from the board as there were more lines cleared than the maximum.

Additionally:
Please add this mode back to the main map. I'm grateful for the possibility of launching this mode from the "info" menu though. But I don't understand why this is hidden now.

**Comment by shoucandanghehe** [comment]
this proposal sounds interesting

**Comment by MrZ626** [comment]
🤔
