### ISSUE TITLE
'O' Piece Can Turn Into Other Pieces.

### ISSUE THREAD

**Issue by Egg-Man-Real** [26F-Studio/Techmino#689]
To reproduce it simply make an area that a T piece (Or in some cases L or J) can be spun into. Then use an O piece and it will change shape to rotate in. Still gives 'O-Spin' bonus.
![6DB1A374-014B-4278-A6F8-7E5AC0D58EF6](https://user-images.githubusercontent.com/104573822/165761789-f649b15e-5d5c-4fcd-94f5-35e2546c6e20.png)

**Comment by MrZ626** [comment]
You found a secret feature!

**Comment by Egg-Man-Real** [comment]
Oh. Thanks for telling me it was a feature lmao
