### ISSUE TITLE
Cannot Load CCLoader on 32bit Android Device

### ISSUE THREAD

**Issue by aaabcatt** [26F-Studio/Techmino#690]
Screenshot with unintended behaviors (*Image(s) Here*):
![Screenshot_20220502-183626](https://user-images.githubusercontent.com/98994398/166227572-58e76d6e-ee84-4992-a101-817c0055f3b7.jpg)
![Screenshot_20220502-183615](https://user-images.githubusercontent.com/98994398/166227577-a457c560-1f43-4657-9c77-0ddcb3470f2f.jpg)

#
If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
--
I dont know how to say it, but i can a little bit explain while i first time installing Techmino in apk on right link github releases, when launching Techmino first time, the error message appears, which the word like these on screenshot.

I dont touch or click anything before launching the app, the error message always show when playing with CCbot, Tech45/99 Mode.

my device is Samsung J7 16 armeabi-v7. OS version 8.1.0

it should work because when i trying to checking the love file with RAR, the libAndroid folder has armeabi-v7 and armv8. 
but it doesn't work on my device.

**Comment by ImpleLee** [comment]
Probably related to how we detect system architecture (current method is https://github.com/26F-Studio/Zframework/blob/7efa52be11227833616a215c58fd12fafec7a678/require.lua#L11#L13).

**Comment by ImpleLee** [comment]
Seems like the architecture called 'armv8l' should be a 32-bit device instead of a 64-bit device.

**Comment by shoucandanghehe** [comment]
can you download [aida64](https://play.google.com/store/apps/details?id=com.finalwire.aida64)？
screenshot the CPU page

**Comment by ImpleLee** [comment]
> can you download [aida64](https://play.google.com/store/apps/details?id=com.finalwire.aida64)？ screenshot the CPU page

We already know the CPU type.
