### ISSUE TITLE
about voice setting

### ISSUE THREAD

**Issue by sakurw** [26F-Studio/Techmino#691]
voice pack setting is not saved and when I close game, voice pack is changed miya

**Comment by MrZ626** [comment]
Should: change setting, apply, then quit setting menu

**Comment by sakurw** [comment]
sure, and I played some games after this
at that time,  voice setting was saved
but I close techmino and start it again, voice setting is not saved

**Comment by sakurw** [comment]
![1](https://user-images.githubusercontent.com/45168417/166317816-c70b00ef-c56c-42fc-a360-dab4bdf74587.png)
![2](https://user-images.githubusercontent.com/45168417/166317827-7592cd9b-3e1e-44fd-8e82-9d6574d1d9be.png)
![3](https://user-images.githubusercontent.com/45168417/166317836-c3695bfe-4a02-47b0-891d-da3ca659fb0a.png)

https://user-images.githubusercontent.com/45168417/166318305-979fd6a2-d2b9-4fcd-a1fc-3010f1ca7a19.mp4

I do it and took a video of the reproduction

**Comment by MrZ626** [comment]
oh wait it's a small bug and I had already fixed it
In previous version "mono" voice pack is disabled by changing setting when launched, and I forgot to delete the code
