### ISSUE TITLE
连接被断开：operation not permitted

### ISSUE THREAD

**Issue by YunfangHou** [26F-Studio/Techmino#740]
macOS Monterey

<img width="1280" alt="ScreenShot 2022-08-13 at 15 27 29" src="https://user-images.githubusercontent.com/53991651/184498622-39756e0c-1766-49db-86c0-62bc86d01e70.png">

**Comment by C29H25N3O5** [comment]
For me too (macOS Ventura developer beta).

**Comment by C29H25N3O5** [comment]
For me it’s:
<img width="1680" alt="Screenshot 2022-08-30 at 01 59 00" src="https://user-images.githubusercontent.com/87485746/187370896-9bd1ad08-9c29-420a-8f26-976eae9cdce6.png">

**Comment by YunfangHou** [comment]
> For me it’s:
> <img alt="Screenshot 2022-08-30 at 01 59 00" width="1680" src="https://user-images.githubusercontent.com/87485746/187370896-9bd1ad08-9c29-420a-8f26-976eae9cdce6.png">

I've got contact with the developer. He told me that the online function is removed. Just regard Techmino as a stand-alone game for now.

They are now developing a new version called [Techmono Galaxy](https://github.com/26F-Studio/Techmino_Galaxy).

**Comment by C29H25N3O5** [comment]
I am part of the team btw

**Comment by C29H25N3O5** [comment]
The online game is really crappy right now and MrZ said he doesn’t want to touch it anymore so we will see

Also Galaxy won’t be released till I guess next year (he literally had just started)

Z酱: 我写了个框架
Z酱: 没想好接下来咋搞 开摆

其实我最近也挺摆的 该肝力(

**Comment by YunfangHou** [comment]
> I am part of the team btw

Wow just found that😉

**Comment by MrZ626** [comment]
Probably solved with new network frontend/backend
