### ISSUE TITLE
Crash when you change the color at custom_field

### ISSUE THREAD

**Issue by Richard969** [26F-Studio/Techmino#743]
Screenshot with crash information (*Image(s) Here*):
![2022-08-19_00-52](https://user-images.githubusercontent.com/62456622/185451382-58f36c06-380c-4022-9d4e-d9e694c082e7.png)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the game to crash, like pressing a key/button (*Details Here*)
1. Go 'Custom Game' -- 'Edit Field'.
2. Press any color button. (eg. Smart, Erase, etc.)

This issue should be reproducible in a newer version than d864802.

**Comment by C29H25N3O5** [comment]
Could reproduce. (iOS 16 dev beta)

**Comment by C29H25N3O5** [comment]
![Screenshot 2022-08-30 at 01 47 19](https://user-images.githubusercontent.com/87485746/187369899-6d685629-c8f9-498d-b184-138e49ebf006.jpg)

**Comment by ImpleLee** [comment]
Reproducible on Android.
