### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by No-Usernam8** [26F-Studio/Techmino#75]
![Capture+_2021-06-07-14-15-48](https://user-images.githubusercontent.com/85512454/121061982-ec670e80-c79a-11eb-9e1f-3e5cdae6a85e.png)

**Comment by shoucandanghehe** [comment]
Will this happen in the current version?

**Comment by shoucandanghehe** [comment]
Yes, server in China.
But I think the cause of this problem should not be this
maybe a dns problem

**Comment by shoucandanghehe** [comment]
@Not-A-Normal-Robot We changed the server. Has this problem been improved?

**Comment by Trebor-Huang** [comment]
Wait is the new server even deployed?

**Comment by shoucandanghehe** [comment]
The server is old, but migrated to Tencent Cloud

**Comment by ParticleG** [comment]
Should be more reliable now. But the online player count could sometimes be inaccurate.

**Comment by ParticleG** [comment]
Next server Techluster's ConnectNode would be distributed on cloud servers. Should totally fix this problem.
