### ISSUE TITLE
Broken CCLoader on linux

### ISSUE THREAD

**Issue by SlawekNowy** [26F-Studio/Techmino#758]
![Przechwycenie obrazu ekranu_2022-10-10_16-05-12](https://user-images.githubusercontent.com/38943477/194885148-8edee86c-0fa2-4845-bc37-7fe04de55120.png)

**Comment by ImpleLee** [comment]
Reproducible. This is due to the new packaging algorithm. @ParticleG is working on it.

**Comment by ParticleG** [comment]
Fixed with #796
