### ISSUE TITLE
点击【联网游戏】提示"连接被断开：connection refused"

### ISSUE THREAD

**Issue by Kevin-free** [26F-Studio/Techmino#767]
Screenshot with unintended behaviors (*Image(s) Here*):

![image](https://user-images.githubusercontent.com/26422757/199973391-c7fd02d3-2e94-4519-9c0b-997a9cb24804.png)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):

中国大陆地区，WIFI 网络下，未开 VPN。
请问是否有玩家群可以加入交流？

**Comment by MrZ626** [comment]
老的联网系统已经弃用了，更新一下
群在关于页面有，切换成英文就是discord，qq频道可以直接搜

**Comment by Kevin-free** [comment]
我是 iOS 在 App Store 下载的，版本 V0.17.6 昏暗 Dim，进入游戏就提示“连接被断开”，也没找到更新的地方啊？到 release 中下载哪个吗？我下了 Techmino_iOS.ipa 无法安装呀。
另外想问下有开发微信小程序之类的吗？我觉得你这游戏做的挺好，就是下载和分享不是很方便。

**Comment by MrZ626** [comment]
等app store的更新过审

**Comment by MrZ626** [comment]
小程序…没想法，不打算走这些路

**Comment by Kevin-free** [comment]
> 小程序…没想法，不打算走这些路

为啥呢？ 我看你的产品做的挺好而且没有广告，那怎么获取收益呢？难道只是自己为爱发电的项目？

**Comment by MrZ626** [comment]
是，兴趣项目，不想拿它挣钱，广告也是故意不打的

**Comment by Kevin-free** [comment]
> 是，兴趣项目，不想拿它挣钱，广告也是故意不打的

真棒👍🏻佩服！我对方块游戏也很感兴趣，最近也想做一款。不过我是后台开发，对前端不是很懂。不知能否请教你一下：
1、项目所用到的 [LOVE](https://indienova.com/indie-game-development/engine-love2d/) 引擎是否只能负责前端逻辑和渲染？
2、此方块游戏的「联网」和其他数据存储功能还是得后台服务实现对吧？

**Comment by MrZ626** [comment]
love2d引擎有官网，功能可以说基本就是“读取设备输入（鼠标键盘触摸屏计时器等），播放音频，绘制图像这些事的几个基本库封装到lua层”
联网是有个后端的，目前是Particle_G在做，跑在朋友的服务器上

**Comment by MrZ626** [comment]
Seems to be a new feature, haven't seen this before
