### ISSUE TITLE
SRS+ setting doesn't do SRS+

### ISSUE THREAD

**Issue by BaronAWC95014** [26F-Studio/Techmino#772]
SRS+ seems to be identical to SRS. the I piece doesn't rotate symmetrically and some 180 kicks don't work.

Screenshot with unintended behaviors (*Image(s) Here*):
<img width="591" alt="Screen Shot 2022-11-08 at 3 55 33 PM" src="https://user-images.githubusercontent.com/43506286/200701774-9dce3a49-2026-4f9b-b3e3-61df403abd2f.png">
despite having SRS+ enabled, i cannot get the I piece to the right of the O with CW or CCW rotation. in SRS+, i should be able to get the I piece to the right with a CW rotation.

<img width="243" alt="Screen Shot 2022-11-08 at 3 57 51 PM" src="https://user-images.githubusercontent.com/43506286/200702059-e5d93bd4-8b0d-463c-b40d-ccc2ba5c4af5.png">
i should be able to use a 180 kick to get the T to jump out 2 blocks up and 1 block to the side. however, it doesn't work.

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
- turn on SRS+ in settings
- test it out in a custom game

**Comment by MrZ626** [comment]
SRS+ in Techmino is not SRS+ in other games
