### ISSUE TITLE
Cannot regeister new account

### ISSUE THREAD

**Issue by M1k0t0** [26F-Studio/Techmino#776]
Client Version: 0.17.8: 暂停 Break
![InGame](https://user-images.githubusercontent.com/58372301/201459204-c96722ba-775a-43d8-8370-379be614b336.png)
The registration function does not work properly, I tested the game on Windows and iOS and neither of them could register.
After checking the api url in the code and using postman to post data externally, see the following return.
![PostMan](https://user-images.githubusercontent.com/58372301/201459146-9736ed5b-6f5a-498c-902e-b91fcd11f78e.png)
As shown, if the way I requested the API is correct, guessing that there are some issues with the email sending service.

**Comment by MrZ626** [comment]
Now e-mail service is down, just wait
