### ISSUE TITLE
Modes that use Attack as a statistic still has a decimal 

### ISSUE THREAD

**Issue by MelloBoo44** [26F-Studio/Techmino#780]
The decimal in the attack statistic (modes such as Sprint 100 attack) is still there, it's unnecessary.

**Comment by MrZ626** [comment]
😨

**Comment by MrZ626** [comment]
I thought again and the conclusion is, why not? Decimal attack is also attack, just too little to send to others. It's reasonable in my view

**Comment by MelloBoo44** [comment]
I've never seen the decimal been used.. How can it not be XX.0?

**Comment by MrZ626** [comment]
Oh it was, now it's gone
Okay I'll delete the .0
~~FASTEST BUG FIX~~

**Comment by MelloBoo44** [comment]
🙃
