### ISSUE TITLE
[Feature Request] Whether to consider adding a two-player cooperative mode？

### ISSUE THREAD

**Issue by Kevin-free** [26F-Studio/Techmino#783]
### Are you considering adding a two-player co-op mode? Similar rules like table tennis doubles. I think it will be fun too!

是否考虑新增双人合作模式？就像乒乓球双打类似的规则。我觉得也会很有趣！

**Comment by Kevin-free** [comment]
> yeah this seems like a cool idea, like TGM2's Doubles mode

Umm... What is TGM2 ?

**Comment by Kevin-free** [comment]
> Tetris The Absolute The Grandmaster 2

Oh I find it. Thanks!

**Comment by MrZ626** [comment]
Too ambiguous to be a proper issue, I think I should close this first
