### ISSUE TITLE
Background selection on mobile

### ISSUE THREAD

**Issue by exoad** [26F-Studio/Techmino#811]
### What feature do you want to suggest to the game?

Give the ability for the game on a mobile platform to be able to set a custom background by opening the default file selector app.

currently on mobile (I am on android/Samsung) clicking the “Use Custom B.G.” will launch a prompt to “drag and drop images” on to the app which isn’t really possible on a mobile platform.

**Comment by user670** [comment]
https://github.com/pcornier/lovepicker

just to dump a potentially useful thing I found while googling (googled "love2d android file picker")

**Comment by SweetSea-ButImNotSweet** [comment]
Update: I have make this
https://github.com/love2d/love-android/issues/256
