### ISSUE TITLE
失去焦点造成的暂停可覆盖报错页面

### ISSUE THREAD

**Issue by Richard969** [26F-Studio/Techmino#820]
Screenshot with unintended behaviors (*Image(s) Here*):
![Peek 2023-01-05 20-00](https://user-images.githubusercontent.com/62456622/210775746-5843ecea-2daa-405b-815f-654ed4b498f6.gif)

(蓝屏为修改源代码方式造成)
If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
1. 玩任意模式
2. 让游戏崩溃
3. 让游戏失去焦点
4. 触发bug

**Comment by Trebor-Huang** [comment]
This is actually hilarious: The focus-lost listener should check whether the game has crashed or not before pausing.
