### ISSUE TITLE
Add installer for Windows

### ISSUE THREAD

**Issue by izwb003** [26F-Studio/Techmino#821]
### What feature do you want to suggest to the game?

Just as the title, for any other OS we can install techmino in the system, like APK for Android, ipa for iOS or pkg for macOS, which means it can be open easily through the UI of the operating system like the home page of Android or the launchpad of macOS, then we can play it easily whenever we want. However for Windows or Linux version we only have an exe file with some dlls, or just an AppImage file. Then if we want to play techmino we have to find the exe or AppImage file manually, that is inconvenient...

So will we consider to post an install program when publishing new releases? It may be done easily (I think...) by packing files with Inno Setup or NSIS, or provide a .tar.gz file for some Linux distributions...?

Thank you for your reading.

**Comment by MrZ626** [comment]
But we already have Linux versions to download, did you meet some problems?

**Comment by izwb003** [comment]
> But we already have Linux versions to download, did you meet some problems?

Yes I know that there is a Linux version, but that file in the release is an AppImage file, I consider this kind of file is some kind of... “green software” you know...
That means it does not require to install to run, but that gives a problem is, we just leave it in the disk, if we want to play it, we have to turn on the file manager program in our Linux distribution, find this AppImage file, click it and run it... this just seems not very convenient...
So what I mean is to make a version that requires to "install" it in the OS, like .tar.gz file with a install script for debian-based Linux distributions. Then users can install it by using tar command and run the install script, then it will appear in the desktop of the OS. Then whenever we want to play it, we can just simply click on the icon of techmino on the desktop, then it will run. People who always play techmino may like it?...

I mainly want to see a install program of techmino for Windows actually, then whenever we want to play techmino we can just find it on the desktop or open the "Start" menu and find techmino then we can play it, but not to open explorer and find techmino.exe manually... That's it.

**Comment by shoucandanghehe** [comment]
For Linux, 0.17.10 should have the `.deb` installer (you can see it's now provided by CI)
Windows installer I actually mentioned (privately) a long time ago, I remember when other developers said ~~"portable applications are much better than installer"~~ (I don't remember exactly, they probably said that)

**Comment by izwb003** [comment]
> For Linux, 0.17.10 should have the `.deb` installer (you can see it's now provided by CI) Windows installer I actually mentioned (privately) a long time ago, I remember when other developers said ~"portable applications are much better than installer"~ (I don't remember exactly, they probably said that)

Aha. Different people have different ideas...

So this is just a suggestion here. As I think if you can accept to turn on Inno Setup and click some keys in the instruction menu after a new version is compiled, then put the generated Setup software in the release, emm, maybe... OK?...

> Perhaps we could simply put a shortcut on the desktop when the game is first played

It's another good idea, but here I want to mention maybe someone will just download it in the "Download" folder and some days he deleted it and made an empty shortcut on the desktop...?

So in my opinion a install wizard is better, a shortcut is another good idea, too.
But anyway, I'm just here to give some suggestions, and... yes, thank you for your time :D
Hope techmino will be better and better in the future.

**Comment by izwb003** [comment]
> I think this can and should be solved by creating a shortcut on the desktop.
> 
> > maybe someone will just download it in the "Download" folder and some days he deleted it and made an empty shortcut on the desktop...?
> 
> Using an installer does not prevent a know-nothing-about-software user from deleting the whole game directory and leaving even more empty shortcuts (on desktop, "start" menu, etc.) (don't think such user would properly find and execute the "uninstall" program).
> 
> 
> Some developer suggested using a .bat file to automatically create the shortcuts, which doesn't seem realistic if the user does not know what a "shortcut" is.

Yep. Different users use the same thing in different ways. Who knows...

Tetr.io chose the solution that when the first time it was open it will ask for UAC and automatically "install" to the system, appear on desktop and start menu, register the uninstall in control panel. I just had the idea by using it and consider that is cool, so here gives me this suggestion.

**Comment by shoucandanghehe** [comment]
@ParticleG  says there will be a need to modify the registry in the future
So we should be make an installer

**Comment by ImpleLee** [comment]
As discussed in QQ group, modifying is not necessary.

**Comment by shoucandanghehe** [comment]
A demo https://github.com/shoucandanghehe/Techmino/actions/runs/3911438061

**Comment by ParticleG** [comment]
love-actions-windows repo has been updated. Wait #829 to merge

**Comment by shoucandanghehe** [comment]
> Wait branch `ci-api-new` to merge

#838
