### ISSUE TITLE
Voice pack oddities

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino#823]
- Miya's volume test voice clips are too long. This creates two problems:
  - Multiple clicks/drags on the volume slider makes multiple of those clips play, overlapping each other
  - Since a voice clip's volume isn't affected by the slider once it has started playing, it can make the slider seem unresponsive (and problematic if you don't want your roommate hear a catgirl coming out of your phone)
- Miku, on the other hand, lacks a volume test clip entirely (maybe repurpose the meow for the volume slider?)

**Comment by shoucandanghehe** [comment]
>   * Multiple clicks/drags on the volume slider makes multiple of those clips play, overlapping each other

I think it's quite distinctive
hope to retain this feature（

>   * Since a voice clip's volume isn't affected by the slider once it has started playing, it can make the slider seem unresponsive (and problematic if you don't want your roommate hear a catgirl coming out of your phone)

But this could indeed be a problem

**Comment by ImpleLee** [comment]
Is this an upstream issue or our own fault? @MrZ626

**Comment by SweetSea-ButImNotSweet** [comment]
> Is this an upstream issue or our own fault? @MrZ626 

Own fault
Since we should stop the previous SFX stream before playing the new one

**Comment by ImpleLee** [comment]
> Since a voice clip's volume isn't affected by the slider once it has started playing

I mean this one.

**Comment by MrZ626** [comment]
> > Since a voice clip's volume isn't affected by the slider once it has started playing
> 
> I mean this one.

not a problem to fix I think
