### ISSUE TITLE
Feature request: option to never use seasonal themes

### ISSUE THREAD

**Issue by User670** [26F-Studio/Techmino#831]
### What feature do you want to suggest to the game?
An option in settings to never apply seasonal themes

**Comment by MrZ626** [comment]
Maybe dislike some title BGMs

**Comment by user670** [comment]
Re Not a robot, I added the "dispute" tag expecting Z wouldn't like this at least, and/or perhaps a few other folks who enjoy the seasonal themes.

As for my problem with the themes, yes song (especially the new year song) but also the color scheme that I don't exactly like.

**Comment by C29H25N3O5** [comment]
Actually I think it would be also reasonable to have the option to ditch all themes whatsoever if the player feels like it
