### ISSUE TITLE
Need an more proper/robust debugger

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#843]
### What feature do you want to suggest to the game?

Ok, I am messing the Techmino's codes to find a way that I can make a offline room (like Techmino 99 mod) but with 200 players by editing a mod. But seem the game crashes before entering the mode, leaves me only one line of log: "memory allocation of XXXXXX bytes failed". No more, without any logs, without game's BSOD/PSOD

So I suggest to have a debugger that will write a log, but this time it's more detailed with a hint of where the game already runs the code. Let me have a little more clues to find and try to fix the bug (if I can)

P/s: the situation is that the game crashes and crashes and sometimes crashes even the graphics. I ran out of ideas, I don't know where the game went wrong, I just know that it crashed when I entered the modified mode. Also I tried to connect LOVE with VSCode to explore the variable but seem the game don't let me do it, btw

**Comment by shoucandanghehe** [comment]
Maybe you can use some debug plugins for vscode.
I think it's too complicated to make a debuger for a game

**Comment by SweetSea-ButImNotSweet** [comment]
> Maybe you can use some debug plugins for vscode.
> I think it's too complicated to make a debuger for a game

Oh yea, I tried to connect VSCode with LOVE by some plugins
There is one thing: how to disable game's BSOD temporarily. Game handle all errors and... I can't simply find bugs without variables
(Because game's BSOD make LOVE still run normally, instead of stopping, so VSCode thinks the code run normally and don't show any errors)

**Comment by MrZ626** [comment]
try to remove `love.errorhandler` function in my code?

**Comment by SweetSea-ButImNotSweet** [comment]
> try to remove `love.errorhandler` function in my code?

Which file?
![image](https://user-images.githubusercontent.com/106439598/215239973-d2177f04-02b1-43e6-a001-c2fbf6a3ee36.png)

**Comment by MrZ626** [comment]
It's in submodule, search in your locale project

**Comment by SweetSea-ButImNotSweet** [comment]
> It's in submodule, search in your local project files

Oh thanks, I found it, In ZFramework folder

**Comment by SweetSea-ButImNotSweet** [comment]
Temporarily I will close it as not planned. Thanks

**Comment by MrZ626** [comment]
btw try-catch in lua is `pcall` function (basic library), have a try if you didn't know it in before, it may helps you debugging
