### ISSUE TITLE
Autorize page error

### ISSUE THREAD

**Issue by TASZITE** [26F-Studio/Techmino#845]
Can't login my 26f account

**Comment by shoucandanghehe** [comment]
It looks like we are having some problems with the server
![image](https://user-images.githubusercontent.com/51957264/216803725-4727ec0a-a9a0-4a6e-a139-1b45930a54d3.png)

**Comment by shoucandanghehe** [comment]
ping @ParticleG

**Comment by ParticleG** [comment]
![image](https://user-images.githubusercontent.com/38580644/216816167-054fd4d7-fdb3-49ef-b9a3-cfb7ad5da665.png)
The connection thread pool may be exhausted due to a memory leak associated with email sending function. Should be fixed now

**Comment by ParticleG** [comment]
https://github.com/26F-Studio/Studio26F/commit/6098811be83e7cd41ba4eafdfba23ea1a7adabf1
