### ISSUE TITLE
Disable smooth animations on multiplayer AI mode.

### ISSUE THREAD

**Issue by AlphaIru** [26F-Studio/Techmino#863]
### What feature do you want to suggest to the game?
Please add a toggle that disables smooth animations of other players, especially against AI: like vs49 and vs99. My laptop cannot handle the process power especially when there are only 30 players left because that's the moment when the AI's animations starts to kick in and lags the game to the point of unplayable. I am suspecting this will happen with online multiplayer too.

**Comment by shoucandanghehe** [comment]
I just did some tests
CPU: i7-12700k with one E-core (approximately equal to i3-9100 single core)
GPU: r9 270x (about equal to Nvidia GTX660)
~~I tried to get LOVE to run on the core graphics card, but it failed (~~
With only 30 players, CPU is fully loaded, GPU takes up to 25%, fps stays at 50+

What hardware are you using
I think the performance requirements of the current game are low enough

**Comment by AlphaIru** [comment]
Not for mine, unfortunately...
Mine is a chromebook:

CPU: AMD A6-9220C
Internal GPU: RADEON R5

5 COMPUTE CORES 2C+3G（2 Threads、1.80 GHz）
