### ISSUE TITLE
Network error while sign up 

### ISSUE THREAD

**Issue by furriest** [26F-Studio/Techmino#879]
Screenshot with unintended behaviors (*Image(s) Here*):
 
![image](https://user-images.githubusercontent.com/3656065/230767877-6f39c809-fb37-42b9-94f8-ec7f399158a5.png)

Steps to reproduce: 
1) go to https://www.studio26f.org/login
2) enter your email and press "continue"
3) on the next screen press "Sign in / Sign up with verification code"

The red banner  "Network error ERR_NETWORK" is displayed.

**Comment by shoucandanghehe** [comment]
ping @ParticleG

**Comment by FERFAIL-TXZ** [comment]
I am having the same issue
