### ISSUE TITLE
Techmino crashing in Tech49 and Tech99 modes

### ISSUE THREAD

**Issue by TASZITE** [26F-Studio/Techmino#883]
the new mechanic that rearranges the Boards in Tech49 and Tech99 modes is crashing my phone.
Operacional System: Android

**Comment by shoucandanghehe** [comment]
What does a crash look like? Is the game gone or is it a blue screen?
If it’s a blue screen, what’s the error code?
What’s your phone model?
What’s your game version?

**Comment by TASZITE** [comment]
My version is last  updated
