### ISSUE TITLE
支持 MacOS Arm64 平台

### ISSUE THREAD

**Issue by bytemain** [26F-Studio/Techmino#891]
### What feature do you want to suggest to the game?

love2d 11.4 已经支持了 macos arm64，我自己在本地玩了下也是可以的

https://github.com/love2d/love/releases/tag/11.4

cold_clear bot 也需要构建出 arm64 版本的。

https://github.com/26F-Studio/cold_clear_ai_love2d_wrapper

**Comment by ImpleLee** [comment]
你尝试了release里的macos版本了吗？
