### ISSUE TITLE
Wrong WIN/LOSE text in Battle?

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#920]
Screenshot with unintended behaviors:
![image](https://github.com/26F-Studio/Techmino/assets/106439598/a1847883-5392-4e3e-9972-567b8ffb1b7c)

If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button:
The "Lose!" text should appear instead of "Win!" text when losing in Battle mode

How to reproduce:
1: Go to any Battle mode
2: Spam Hard Drop key or do anything to lose all lives and the "Game over!" screen appear. As this time the "Win!" text will appear

**Comment by shoucandanghehe** [comment]
![Screenshot_2023-07-24-11-39-57-022_com miui gallery](https://github.com/26F-Studio/Techmino/assets/51957264/3e4794bc-f290-470d-932d-de701004dbfc)
This is correct, because it is the bot's field that shows win, you can see that the player's field shows lose

**Comment by SweetSea-ButImNotSweet** [comment]
> ![Screenshot_2023-07-24-11-39-57-022_com miui gallery](https://user-images.githubusercontent.com/51957264/255467274-3e4794bc-f290-470d-932d-de701004dbfc.jpg) This is correct, because it is the bot's field that shows win, you can see that the player's field shows lose

Wait! So the bot's board should not appear in front of player because it can cause confusing

**Comment by shoucandanghehe** [comment]
Maybe the animation of the bot field moving is too fast

**Comment by SweetSea-ButImNotSweet** [comment]
> Maybe the animation of the bot field moving is too fast

I think remove bot field moving animation maybe better (or not?)

**Comment by ImpleLee** [comment]
I don't think showing the bot's field and "win" in local fight is a good idea.
