### ISSUE TITLE
Weird output when transforming Vietnamese text from uppercase to lowercase (and vice-versa)

### ISSUE THREAD

**Issue by SweetSea-ButImNotSweet** [26F-Studio/Techmino#937]
~~(@C29H25N3O5 please help me to add suitable tag after that)~~

# Screenshot with unintended behaviors (*Image(s) Here*):
(Not related to Unikey or EVKey or any IME apps, just show the configuration that make sure I am using the right one)

Precomposed Unicode<br>the encoding that be used most in Vietnamese community
| | |
|-|-|
| ![image](https://github.com/26F-Studio/Techmino/assets/106439598/f43b17b2-2dde-4288-8523-eaf45aece952)| ![image](https://github.com/26F-Studio/Techmino/assets/106439598/218137dc-8f25-4714-9455-0ac0627c0d6d)|
No letter with accent mark is transforming properly

Composed Unicode - this one is rarely use but still used in some cases (mostly for backward compatibility)
| | |
|:-|:-|
| ![image](https://github.com/26F-Studio/Techmino/assets/106439598/8e6115ef-63b2-4e28-8056-25ef902138c1) | ![image](https://github.com/26F-Studio/Techmino/assets/106439598/46ff2ce3-d16f-4e82-9094-d39346cceb7a) |
Looks better than precomposed one but still not good enough

# If you can reproduce it, write the steps here. If you can't, try to describe what causes the unintended behavior, like pressing a key/button (*Details Here*):
It can be reproduceable in both Windows, Linux and MacOS if you use Unikey or EVKey.
But writing a tutorial here is complicated and unnecessary because it requires IME installed
(had a nightmare with C29H25N3O5 when helping him to type Vietnamese with EVKey 3 (last EVKey version support MacOS - no English UI make me pain)

Instead you can copy this text and just paste it into Lua
* Precomposed Unicode:  ```ĐÂY CHỈ LÀ MỘT VĂN BẢN BÌNH THƯỜNG``` (This is just a normal text)
    UTF+8 points: ```C4 90 C3 82 59 20 43 48 E1 BB 88 20 4C C3 80 20 4D E1 BB 98 54 20 56 C4 82 4E 20 42 E1 BA A2 4E 20 42 C3 8C 4E 48 20 54 48 C6 AF E1 BB 9C 4E 47```

* Composed Unicode: ```ĐÂY CHỈ LÀ MỘT VĂN BẢN BÌNH THƯỜNG```
    UTF+8 points: ```C4 90 C3 82 59 20 43 48 49 CC 89 20 4C 41 CC 80 20 4D C3 94 CC A3 54 20 56 C4 82 4E 20 42 41 CC 89 4E 20 42 49 CC 80 4E 48 20 54 48 C6 AF C6 A0 CC 80 4E 47```

(Converted with https://r12a.github.io/app-conversion/)

# Idea to fix
For now we have this library ``slnunicode`` (C29H25N3O5 already sent to MrZ but at the time I was writing this he hadn't response yet)
Can use this library to transforming characters better

**Comment by C29H25N3O5** [comment]
This is true for any accented letters.

**Comment by MrZ626** [comment]
it's a C library, using this means some random device may cannot load it without much info, we should find a pure lua one

**Comment by MrZ626** [comment]
is there any codepoint sheet about upper/lower case letters? I can make one myself

**Comment by SweetSea-ButImNotSweet** [comment]
> is there any codepoint sheet about upper/lower case letters? I can make one myself

Not now but I will make one later
(Off-topic: maybe I will export it to .csv? Just in case)

**Comment by SweetSea-ButImNotSweet** [comment]
> is there any codepoint sheet about upper/lower case letters? I can make one myself

I think I can make a codepoints table for all languages Techmino supported first

**Comment by SweetSea-ButImNotSweet** [comment]
Fixed in 519f84a8044e7a3e122c2eaa1dcd3b607a8549b0
